/**
 * Brisbane City Council Overlay Layers
 *
 * Comprehensive planning overlays from Brisbane City Plan 2014
 * Source: Brisbane City Council Open Spatial Data
 * https://spatial-brisbane.opendata.arcgis.com/
 */

import { OverlayLayer } from './types';

const BCC_ARCGIS = 'https://services2.arcgis.com/dEKgZETqwmDAh1rP/arcgis/rest/services';
const UU_ARCGIS = 'https://services3.arcgis.com/ocUCNI2h4moKOpKX/arcgis/rest/services';

export const BRISBANE_COUNCIL_LAYERS: OverlayLayer[] = [
  // ============================================================================
  // BOUNDARIES
  // ============================================================================
  {
    id: 'brisbane-property-boundaries',
    name: 'Property Boundaries',
    category: 'boundaries',
    description: 'Cadastral property boundaries (lot/plan)',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: {
      bounds: [152.66, -27.54, 153.32, -27.05],
      states: ['QLD'],
      councils: ['brisbane'],
    },
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/property_boundaries_parcel/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.8,
      minZoom: 15,
      maxZoom: 22,
      fillColor: 'transparent',
      strokeColor: '#6b7280',
      strokeWidth: 1,
    },
    quality: 'authoritative',
    tags: ['cadastre', 'property', 'boundaries', 'lots'],
  },

  // ============================================================================
  // PLANNING & ZONING
  // ============================================================================
  {
    id: 'brisbane-zoning',
    name: 'Zoning',
    category: 'planning',
    description: 'City Plan 2014 zoning designations',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: {
      bounds: [152.66, -27.54, 153.32, -27.05],
      states: ['QLD'],
      councils: ['brisbane'],
    },
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/Zoning/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.5,
      minZoom: 10,
      maxZoom: 22,
      legend: [
        { label: 'Low Density Residential', color: '#ffffbe' },
        { label: 'Low-Medium Density Residential', color: '#ffcc99' },
        { label: 'Medium Density Residential', color: '#ff9966' },
        { label: 'High Density Residential', color: '#cc3333' },
        { label: 'Centre', color: '#0066cc' },
        { label: 'Mixed Use', color: '#ff6600' },
        { label: 'Industry', color: '#9933ff' },
        { label: 'Community Facilities', color: '#ffff00' },
        { label: 'Open Space', color: '#00cc00' },
        { label: 'Special Purpose', color: '#999999' },
      ],
    },
    quality: 'authoritative',
    lastUpdated: '2025-01-20',
    tags: ['zoning', 'land-use', 'planning'],
  },
  {
    id: 'brisbane-neighbourhood-plans',
    name: 'Neighbourhood Plans',
    category: 'planning',
    description: 'Neighbourhood plan boundaries',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: {
      bounds: [152.66, -27.54, 153.32, -27.05],
      states: ['QLD'],
      councils: ['brisbane'],
    },
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/Neighbourhood_Plan_boundaries/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.4,
      minZoom: 11,
      maxZoom: 22,
      fillColor: '#8b5cf6',
      strokeColor: '#6d28d9',
      strokeWidth: 2,
    },
    quality: 'authoritative',
    tags: ['neighbourhood-plan', 'local-plan', 'planning'],
  },

  // ============================================================================
  // FLOOD HAZARDS - AWARENESS LAYERS (Official FAM styling)
  // Colors and labels match Brisbane Flood Awareness Map (fam.brisbane.qld.gov.au)
  // ============================================================================
  {
    id: 'brisbane-flood-awareness-overall',
    name: 'Flood Likelihood (All Sources)',
    category: 'hazards',
    description: 'Combined flood likelihood from river, creek, overland and storm tide',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: {
      bounds: [152.66, -27.54, 153.32, -27.05],
      states: ['QLD'],
      councils: ['brisbane'],
    },
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/Flood_Awareness_Flood_Risk_Overall/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.7,
      minZoom: 10,
      maxZoom: 22,
      legend: [
        { label: 'High likelihood (5% annual)', color: '#2166ac' },
        { label: 'Medium likelihood (1% annual)', color: '#67a9cf' },
        { label: 'Low likelihood (0.2% annual)', color: '#d1e5f0' },
        { label: 'Very low likelihood (0.05% annual)', color: '#f7f7f7' },
      ],
    },
    quality: 'authoritative',
    tags: ['flood', 'awareness', 'risk', 'combined', 'fam'],
  },
  {
    id: 'brisbane-flood-awareness-river',
    name: 'Flood Awareness - River',
    category: 'hazards',
    description: 'Brisbane River flood likelihood zones',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: {
      bounds: [152.66, -27.54, 153.32, -27.05],
      states: ['QLD'],
      councils: ['brisbane'],
    },
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/Flood_Awareness_River/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.7,
      minZoom: 10,
      maxZoom: 22,
      legend: [
        { label: 'High likelihood (5% annual)', color: '#2166ac' },
        { label: 'Medium likelihood (1% annual)', color: '#67a9cf' },
        { label: 'Low likelihood (0.2% annual)', color: '#d1e5f0' },
        { label: 'Very low likelihood (0.05% annual)', color: '#f7f7f7' },
      ],
    },
    quality: 'authoritative',
    tags: ['flood', 'river', 'awareness', 'fam'],
  },
  {
    id: 'brisbane-flood-awareness-creek',
    name: 'Flood Awareness - Creek',
    category: 'hazards',
    description: 'Creek and waterway flood likelihood zones',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: {
      bounds: [152.66, -27.54, 153.32, -27.05],
      states: ['QLD'],
      councils: ['brisbane'],
    },
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/Flood_Awareness_Creek/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.7,
      minZoom: 10,
      maxZoom: 22,
      legend: [
        { label: 'High likelihood (5% annual)', color: '#2166ac' },
        { label: 'Medium likelihood (1% annual)', color: '#67a9cf' },
        { label: 'Low likelihood (0.2% annual)', color: '#d1e5f0' },
        { label: 'Very low likelihood (0.05% annual)', color: '#f7f7f7' },
      ],
    },
    quality: 'authoritative',
    tags: ['flood', 'creek', 'awareness', 'fam'],
  },
  {
    id: 'brisbane-flood-awareness-overland',
    name: 'Flood Awareness - Overland Flow',
    category: 'hazards',
    description: 'Overland flow flood impact zones',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: {
      bounds: [152.66, -27.54, 153.32, -27.05],
      states: ['QLD'],
      councils: ['brisbane'],
    },
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/Flood_Awareness_Overland_Flow/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.7,
      minZoom: 12,
      maxZoom: 22,
      fillColor: '#d4b896',
      strokeColor: '#5e3c26',
      legend: [
        { label: 'High impact', color: '#5e3c26' },
        { label: 'Medium impact', color: '#d4b896' },
        { label: 'Low impact', color: '#f5e6d3' },
      ],
    },
    quality: 'authoritative',
    tags: ['flood', 'overland', 'awareness', 'fam'],
  },
  // Historic flood extents
  {
    id: 'brisbane-flood-historic-2022',
    name: 'Historic Flood - February 2022',
    category: 'hazards',
    description: 'Observed flood extent from February 2022 event',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: {
      bounds: [152.66, -27.54, 153.32, -27.05],
      states: ['QLD'],
      councils: ['brisbane'],
    },
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/Flood_Awareness_Historic_Brisbane_River_and_Creek_Floods_Feb2022/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.6,
      minZoom: 10,
      maxZoom: 22,
      fillColor: '#f4a7b9',
      strokeColor: '#e05780',
      legend: [
        { label: 'February 2022 extent', color: '#f4a7b9' },
      ],
    },
    quality: 'authoritative',
    tags: ['flood', 'historic', '2022', 'fam'],
  },
  {
    id: 'brisbane-flood-historic-2011',
    name: 'Historic Flood - January 2011',
    category: 'hazards',
    description: 'Observed flood extent from January 2011 event',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: {
      bounds: [152.66, -27.54, 153.32, -27.05],
      states: ['QLD'],
      councils: ['brisbane'],
    },
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/Flood_Awareness_Historic_Brisbane_River_Floods_Jan2011/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.6,
      minZoom: 10,
      maxZoom: 22,
      fillColor: '#7fcdbb',
      strokeColor: '#41ae76',
      legend: [
        { label: 'January 2011 extent', color: '#7fcdbb' },
      ],
    },
    quality: 'authoritative',
    tags: ['flood', 'historic', '2011', 'fam'],
  },
  {
    id: 'brisbane-flood-historic-1974',
    name: 'Historic Flood - January 1974',
    category: 'hazards',
    description: 'Observed flood extent from January 1974 event',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: {
      bounds: [152.66, -27.54, 153.32, -27.05],
      states: ['QLD'],
      councils: ['brisbane'],
    },
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/Flood_Awareness_Historic_Brisbane_River_Floods_Jan1974/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.6,
      minZoom: 10,
      maxZoom: 22,
      fillColor: '#9e9ac8',
      strokeColor: '#756bb1',
      legend: [
        { label: 'January 1974 extent', color: '#9e9ac8' },
      ],
    },
    quality: 'authoritative',
    tags: ['flood', 'historic', '1974', 'fam'],
  },

  // ============================================================================
  // FLOOD HAZARDS - PLANNING OVERLAYS (Official City Plan overlays)
  // These are the regulatory flood planning overlays from Brisbane City Plan
  // ============================================================================
  {
    id: 'brisbane-flood-river',
    name: 'Flood Planning - Brisbane River',
    category: 'hazards',
    description: 'Brisbane River flood planning areas (1-5) - City Plan overlay',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: {
      bounds: [152.66, -27.54, 153.32, -27.05],
      states: ['QLD'],
      councils: ['brisbane'],
    },
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/Flood_overlay_Brisbane_River_flood_planning_area/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.6,
      minZoom: 10,
      maxZoom: 22,
      legend: [
        { label: 'Area 1 (Highest Risk)', color: '#08306b' },
        { label: 'Area 2a', color: '#2171b5' },
        { label: 'Area 2b', color: '#4292c6' },
        { label: 'Area 3', color: '#6baed6' },
        { label: 'Area 4', color: '#9ecae1' },
        { label: 'Area 5', color: '#c6dbef' },
      ],
    },
    quality: 'authoritative',
    tags: ['flood', 'river', 'hazard', 'brisbane-river', 'planning'],
  },
  {
    id: 'brisbane-flood-creek',
    name: 'Flood - Creek/Waterway',
    category: 'hazards',
    description: 'Creek and waterway flood planning areas',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: {
      bounds: [152.66, -27.54, 153.32, -27.05],
      states: ['QLD'],
      councils: ['brisbane'],
    },
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/Flood_overlay_Creek_waterway_flood_planning_area/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.6,
      minZoom: 10,
      maxZoom: 22,
      legend: [
        { label: 'Area 1 (Highest Risk)', color: '#08306b' },
        { label: 'Area 2', color: '#2171b5' },
        { label: 'Area 3', color: '#4292c6' },
        { label: 'Area 4', color: '#6baed6' },
        { label: 'Area 5', color: '#9ecae1' },
      ],
    },
    quality: 'authoritative',
    tags: ['flood', 'creek', 'waterway', 'hazard'],
  },
  {
    id: 'brisbane-flood-overland',
    name: 'Flood - Overland Flow',
    category: 'hazards',
    description: 'Overland flow flood planning areas',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: {
      bounds: [152.66, -27.54, 153.32, -27.05],
      states: ['QLD'],
      councils: ['brisbane'],
    },
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/Flood_overlay_Overland_flow/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.5,
      minZoom: 12,
      maxZoom: 22,
      fillColor: '#60a5fa',
      strokeColor: '#2563eb',
      strokeWidth: 1,
    },
    quality: 'authoritative',
    tags: ['flood', 'overland-flow', 'stormwater', 'hazard'],
  },

  // ============================================================================
  // OTHER HAZARDS
  // ============================================================================
  {
    id: 'brisbane-bushfire',
    name: 'Bushfire Overlay',
    category: 'hazards',
    description: 'Bushfire hazard areas and buffer zones',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: {
      bounds: [152.66, -27.54, 153.32, -27.05],
      states: ['QLD'],
      councils: ['brisbane'],
    },
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/Bushfire_overlay/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.6,
      minZoom: 10,
      maxZoom: 22,
      legend: [
        { label: 'High Hazard Area', color: '#dc2626' },
        { label: 'Medium Hazard Area', color: '#f97316' },
        { label: 'Potential Impact Buffer', color: '#fbbf24' },
      ],
    },
    quality: 'authoritative',
    tags: ['bushfire', 'fire', 'hazard', 'bal'],
  },
  {
    id: 'brisbane-landslide',
    name: 'Landslide Overlay',
    category: 'hazards',
    description: 'Landslide susceptibility areas',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: {
      bounds: [152.66, -27.54, 153.32, -27.05],
      states: ['QLD'],
      councils: ['brisbane'],
    },
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/Landslide_overlay/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.6,
      minZoom: 10,
      maxZoom: 22,
      fillColor: '#92400e',
      strokeColor: '#78350f',
      strokeWidth: 1,
    },
    quality: 'authoritative',
    tags: ['landslide', 'geotechnical', 'slope', 'hazard'],
  },
  {
    id: 'brisbane-storm-tide',
    name: 'Coastal - Storm Tide',
    category: 'hazards',
    description: 'Storm tide inundation areas',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: {
      bounds: [152.66, -27.54, 153.32, -27.05],
      states: ['QLD'],
      councils: ['brisbane'],
    },
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/Coastal_hazard_overlay_Storm_tide/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.6,
      minZoom: 10,
      maxZoom: 22,
      legend: [
        { label: 'High Storm Tide', color: '#1e40af' },
        { label: 'Medium Storm Tide', color: '#06b6d4' },
      ],
    },
    quality: 'authoritative',
    tags: ['coastal', 'storm-tide', 'inundation', 'hazard'],
  },

  // ============================================================================
  // ENVIRONMENT
  // ============================================================================
  {
    id: 'brisbane-biodiversity',
    name: 'Biodiversity Areas',
    category: 'environment',
    description: 'Areas of ecological significance',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: {
      bounds: [152.66, -27.54, 153.32, -27.05],
      states: ['QLD'],
      councils: ['brisbane'],
    },
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/Biodiversity_areas_overlay_Biodiversity_areas/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.5,
      minZoom: 10,
      maxZoom: 22,
      legend: [
        { label: 'High Ecological Significance', color: '#166534' },
        { label: 'General Ecological Significance', color: '#4ade80' },
        { label: 'Strategic Biodiversity Area', color: '#86efac' },
      ],
    },
    quality: 'authoritative',
    tags: ['biodiversity', 'ecology', 'vegetation', 'environment'],
  },
  {
    id: 'brisbane-koala-habitat',
    name: 'Koala Habitat Areas',
    category: 'environment',
    description: 'Koala habitat protection areas',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: {
      bounds: [152.66, -27.54, 153.32, -27.05],
      states: ['QLD'],
      councils: ['brisbane'],
    },
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/Biodiversity_areas_overlay_Koala_habitat_areas/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.5,
      minZoom: 10,
      maxZoom: 22,
      fillColor: '#65a30d',
      strokeColor: '#3f6212',
      strokeWidth: 1,
    },
    quality: 'authoritative',
    tags: ['koala', 'habitat', 'wildlife', 'environment'],
  },

  // ============================================================================
  // PLANNING CONTROLS
  // ============================================================================
  {
    id: 'brisbane-building-height',
    name: 'Building Height Limits',
    category: 'planning',
    description: 'Maximum building height zones',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: {
      bounds: [152.66, -27.54, 153.32, -27.05],
      states: ['QLD'],
      councils: ['brisbane'],
    },
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/Building_height_overlay/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.5,
      minZoom: 12,
      maxZoom: 22,
      legend: [
        { label: '3 storeys (9.5m)', color: '#fef3c7' },
        { label: '5 storeys (15m)', color: '#fde68a' },
        { label: '8 storeys (25m)', color: '#fcd34d' },
        { label: '15 storeys (45m)', color: '#f59e0b' },
        { label: '25+ storeys', color: '#d97706' },
      ],
    },
    quality: 'authoritative',
    tags: ['height', 'building', 'storeys', 'planning'],
  },
  {
    id: 'brisbane-character-residential',
    name: 'Character Residential',
    category: 'planning',
    description: 'Traditional building character areas with design controls',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: {
      bounds: [152.66, -27.54, 153.32, -27.05],
      states: ['QLD'],
      councils: ['brisbane'],
    },
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/Traditional_building_character_overlay/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.5,
      minZoom: 12,
      maxZoom: 22,
      legend: [
        { label: 'Pre-1946 Character', color: '#c084fc' },
        { label: 'Demolition Control', color: '#a855f7' },
      ],
    },
    quality: 'authoritative',
    tags: ['character', 'heritage', 'traditional', 'demolition', 'planning'],
  },
  {
    id: 'brisbane-airport-environs',
    name: 'Airport Environs Overlay',
    category: 'planning',
    description: 'Airport noise corridors and height restrictions',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: {
      bounds: [152.66, -27.54, 153.32, -27.05],
      states: ['QLD'],
      councils: ['brisbane'],
    },
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/Airport_environs_overlay/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.4,
      minZoom: 10,
      maxZoom: 22,
      legend: [
        { label: 'ANEF 25-30 (High Noise)', color: '#ef4444' },
        { label: 'ANEF 20-25', color: '#f97316' },
        { label: 'Light Limitation', color: '#fbbf24' },
        { label: 'Height Restriction', color: '#3b82f6' },
      ],
    },
    quality: 'authoritative',
    tags: ['airport', 'noise', 'anef', 'flight-path', 'planning'],
  },
  {
    id: 'brisbane-transport-noise',
    name: 'Transport Noise Corridor',
    category: 'planning',
    description: 'Road and rail noise impact areas',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: {
      bounds: [152.66, -27.54, 153.32, -27.05],
      states: ['QLD'],
      councils: ['brisbane'],
    },
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/Transport_noise_corridor_overlay/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.5,
      minZoom: 12,
      maxZoom: 22,
      legend: [
        { label: 'Road Noise Corridor', color: '#64748b' },
        { label: 'Rail Noise Corridor', color: '#475569' },
      ],
    },
    quality: 'authoritative',
    tags: ['noise', 'transport', 'road', 'rail', 'planning'],
  },
  {
    id: 'brisbane-waterway-corridor',
    name: 'Waterway Corridors',
    category: 'environment',
    description: 'Natural waterway setback and buffer areas',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: {
      bounds: [152.66, -27.54, 153.32, -27.05],
      states: ['QLD'],
      councils: ['brisbane'],
    },
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/Waterway_corridors_overlay/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.5,
      minZoom: 12,
      maxZoom: 22,
      legend: [
        { label: 'Core Waterway', color: '#0ea5e9' },
        { label: 'Corridor Buffer', color: '#7dd3fc' },
      ],
    },
    quality: 'authoritative',
    tags: ['waterway', 'creek', 'river', 'setback', 'environment'],
  },
  {
    id: 'brisbane-scenic-amenity',
    name: 'Scenic Amenity',
    category: 'environment',
    description: 'Areas of high scenic/visual amenity value',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: {
      bounds: [152.66, -27.54, 153.32, -27.05],
      states: ['QLD'],
      councils: ['brisbane'],
    },
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/Scenic_amenity_overlay/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.4,
      minZoom: 10,
      maxZoom: 22,
      legend: [
        { label: 'Ridge Line', color: '#059669' },
        { label: 'Scenic Route', color: '#10b981' },
        { label: 'Significant Vegetation', color: '#34d399' },
      ],
    },
    quality: 'authoritative',
    tags: ['scenic', 'amenity', 'visual', 'views', 'environment'],
  },
  {
    id: 'brisbane-extractive-resources',
    name: 'Extractive Resources',
    category: 'planning',
    description: 'Extractive industry (quarry) buffer areas',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: {
      bounds: [152.66, -27.54, 153.32, -27.05],
      states: ['QLD'],
      councils: ['brisbane'],
    },
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/Extractive_resources_overlay/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.5,
      minZoom: 10,
      maxZoom: 22,
      legend: [
        { label: 'Key Resource Area', color: '#78716c' },
        { label: 'Separation Area', color: '#a8a29e' },
      ],
    },
    quality: 'authoritative',
    tags: ['extractive', 'quarry', 'mining', 'resources', 'planning'],
  },
  {
    id: 'brisbane-special-entertainment',
    name: 'Special Entertainment Precinct',
    category: 'planning',
    description: 'Areas with relaxed noise controls for entertainment venues',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: {
      bounds: [152.66, -27.54, 153.32, -27.05],
      states: ['QLD'],
      councils: ['brisbane'],
    },
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/Special_entertainment_precinct_overlay/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.5,
      minZoom: 12,
      maxZoom: 22,
      fillColor: '#f472b6',
      strokeColor: '#ec4899',
      strokeWidth: 2,
    },
    quality: 'authoritative',
    tags: ['entertainment', 'fortitude-valley', 'noise', 'nightlife', 'planning'],
  },

  // ============================================================================
  // HERITAGE
  // ============================================================================
  {
    id: 'brisbane-heritage',
    name: 'Heritage Overlay',
    category: 'heritage',
    description: 'Local heritage places and adjoining areas',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: {
      bounds: [152.66, -27.54, 153.32, -27.05],
      states: ['QLD'],
      councils: ['brisbane'],
    },
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/Heritage_overlay/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.6,
      minZoom: 12,
      maxZoom: 22,
      legend: [
        { label: 'Local Heritage Place', color: '#7c3aed' },
        { label: 'Area Adjoining Heritage', color: '#c4b5fd' },
      ],
    },
    quality: 'authoritative',
    tags: ['heritage', 'historic', 'conservation'],
  },

  // ============================================================================
  // INFRASTRUCTURE - LGIP (Local Government Infrastructure Plan)
  // ============================================================================
  {
    id: 'brisbane-lgip-stormwater-existing',
    name: 'LGIP Stormwater - Existing',
    category: 'infrastructure',
    description: 'Existing stormwater infrastructure (PFTI)',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: {
      bounds: [152.66, -27.54, 153.32, -27.05],
      states: ['QLD'],
      councils: ['brisbane'],
    },
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/City_Plan_2014_LGIP_PFTI_Stormwater_Existing/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.7,
      minZoom: 12,
      maxZoom: 22,
      fillColor: '#0ea5e9',
      strokeColor: '#0284c7',
      strokeWidth: 2,
    },
    quality: 'authoritative',
    tags: ['stormwater', 'drainage', 'infrastructure', 'lgip', 'existing'],
  },
  {
    id: 'brisbane-lgip-stormwater-future',
    name: 'LGIP Stormwater - Future',
    category: 'infrastructure',
    description: 'Planned future stormwater infrastructure (PFTI)',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: {
      bounds: [152.66, -27.54, 153.32, -27.05],
      states: ['QLD'],
      councils: ['brisbane'],
    },
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/City_Plan_2014_LGIP_PFTI_Stormwater_Future/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.6,
      minZoom: 12,
      maxZoom: 22,
      fillColor: '#38bdf8',
      strokeColor: '#0ea5e9',
      strokeWidth: 2,
      lineDashArray: [5, 5],
    },
    quality: 'authoritative',
    tags: ['stormwater', 'drainage', 'infrastructure', 'lgip', 'future', 'planned'],
  },
  {
    id: 'brisbane-lgip-transport-existing',
    name: 'LGIP Transport - Existing',
    category: 'infrastructure',
    description: 'Existing transport infrastructure (PFTI)',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: {
      bounds: [152.66, -27.54, 153.32, -27.05],
      states: ['QLD'],
      councils: ['brisbane'],
    },
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/City_Plan_2014_LGIP_PFTI_Transport_Existing/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.7,
      minZoom: 10,
      maxZoom: 22,
      fillColor: '#f97316',
      strokeColor: '#ea580c',
      strokeWidth: 2,
    },
    quality: 'authoritative',
    tags: ['transport', 'roads', 'infrastructure', 'lgip', 'existing'],
  },
  {
    id: 'brisbane-lgip-transport-future',
    name: 'LGIP Transport - Future',
    category: 'infrastructure',
    description: 'Planned future transport infrastructure (PFTI)',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: {
      bounds: [152.66, -27.54, 153.32, -27.05],
      states: ['QLD'],
      councils: ['brisbane'],
    },
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/City_Plan_2014_LGIP_PFTI_Transport_Future/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.6,
      minZoom: 10,
      maxZoom: 22,
      fillColor: '#fb923c',
      strokeColor: '#f97316',
      strokeWidth: 2,
      lineDashArray: [5, 5],
    },
    quality: 'authoritative',
    tags: ['transport', 'roads', 'infrastructure', 'lgip', 'future', 'planned'],
  },
  {
    id: 'brisbane-lgip-parks-existing',
    name: 'LGIP Parks & Community - Existing',
    category: 'infrastructure',
    description: 'Existing parks and community facilities (PFTI)',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: {
      bounds: [152.66, -27.54, 153.32, -27.05],
      states: ['QLD'],
      councils: ['brisbane'],
    },
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/City_Plan_2014_LGIP_PFTI_Parks_and_Community_Facilities_Existing/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.6,
      minZoom: 10,
      maxZoom: 22,
      fillColor: '#22c55e',
      strokeColor: '#16a34a',
      strokeWidth: 2,
    },
    quality: 'authoritative',
    tags: ['parks', 'community', 'recreation', 'infrastructure', 'lgip', 'existing'],
  },
  {
    id: 'brisbane-lgip-parks-future',
    name: 'LGIP Parks & Community - Future',
    category: 'infrastructure',
    description: 'Planned future parks and community facilities (PFTI)',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: {
      bounds: [152.66, -27.54, 153.32, -27.05],
      states: ['QLD'],
      councils: ['brisbane'],
    },
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/City_Plan_2014_LGIP_PFTI_Parks_and_Community_Facilities_Future/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.5,
      minZoom: 10,
      maxZoom: 22,
      fillColor: '#4ade80',
      strokeColor: '#22c55e',
      strokeWidth: 2,
      lineDashArray: [5, 5],
    },
    quality: 'authoritative',
    tags: ['parks', 'community', 'recreation', 'infrastructure', 'lgip', 'future', 'planned'],
  },
  {
    id: 'brisbane-lgip-service-catchments',
    name: 'LGIP Service Catchments',
    category: 'infrastructure',
    description: 'Local government infrastructure plan service catchment areas',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: {
      bounds: [152.66, -27.54, 153.32, -27.05],
      states: ['QLD'],
      councils: ['brisbane'],
    },
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/City_Plan_2014_LGIP_Service_Catchments/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.3,
      minZoom: 10,
      maxZoom: 22,
      fillColor: '#a855f7',
      strokeColor: '#9333ea',
      strokeWidth: 1,
    },
    quality: 'authoritative',
    tags: ['service-catchment', 'infrastructure', 'lgip', 'planning'],
  },
  {
    id: 'brisbane-sewer-areas',
    name: 'Sewer Service Areas',
    category: 'infrastructure',
    description: 'Detail plan areas for sewer infrastructure',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: {
      bounds: [152.66, -27.54, 153.32, -27.05],
      states: ['QLD'],
      councils: ['brisbane'],
    },
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/detail_plan_areas_sewer/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.4,
      minZoom: 10,
      maxZoom: 22,
      fillColor: '#8b5cf6',
      strokeColor: '#7c3aed',
      strokeWidth: 1,
    },
    quality: 'authoritative',
    tags: ['sewer', 'wastewater', 'infrastructure', 'utilities'],
  },
  {
    id: 'brisbane-high-voltage-powerlines',
    name: 'High Voltage Powerlines',
    category: 'infrastructure',
    description: 'High voltage electricity transmission lines',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: {
      bounds: [152.66, -27.54, 153.32, -27.05],
      states: ['QLD'],
      councils: ['brisbane'],
    },
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/Regional_infrastructure_corridors_and_substations_overlay_High_voltage_powerline/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.8,
      minZoom: 10,
      maxZoom: 22,
      strokeColor: '#dc2626',
      strokeWidth: 2,
    },
    quality: 'authoritative',
    tags: ['power', 'electricity', 'high-voltage', 'transmission', 'infrastructure'],
  },
  {
    id: 'brisbane-high-voltage-easements',
    name: 'High Voltage Easements',
    category: 'infrastructure',
    description: 'Easements for high voltage electricity infrastructure',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: {
      bounds: [152.66, -27.54, 153.32, -27.05],
      states: ['QLD'],
      councils: ['brisbane'],
    },
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/Regional_infrastructure_corridors_and_substations_overlay_High_voltage_easements/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.5,
      minZoom: 12,
      maxZoom: 22,
      fillColor: '#fca5a5',
      strokeColor: '#dc2626',
      strokeWidth: 1,
    },
    quality: 'authoritative',
    tags: ['power', 'electricity', 'easement', 'infrastructure'],
  },
  {
    id: 'brisbane-substations',
    name: 'High Voltage Substations',
    category: 'infrastructure',
    description: 'Electrical substations',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: {
      bounds: [152.66, -27.54, 153.32, -27.05],
      states: ['QLD'],
      councils: ['brisbane'],
    },
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/CP2014_Regional_infrastructure_overlay_High_voltage_substations/FeatureServer/1`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.8,
      minZoom: 10,
      maxZoom: 22,
      fillColor: '#fbbf24',
      strokeColor: '#f59e0b',
      strokeWidth: 2,
    },
    quality: 'authoritative',
    tags: ['power', 'electricity', 'substation', 'infrastructure'],
  },
  {
    id: 'brisbane-petroleum-pipelines',
    name: 'Petroleum Pipelines',
    category: 'infrastructure',
    description: 'Major petroleum and gas pipeline corridors',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: {
      bounds: [152.66, -27.54, 153.32, -27.05],
      states: ['QLD'],
      councils: ['brisbane'],
    },
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/Regional_infrastructure_corridors_and_substations_overlay_Petroleum_pipelines/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.8,
      minZoom: 10,
      maxZoom: 22,
      strokeColor: '#7c3aed',
      strokeWidth: 3,
    },
    quality: 'authoritative',
    tags: ['petroleum', 'gas', 'pipeline', 'infrastructure'],
  },
  {
    id: 'brisbane-major-transport-infrastructure',
    name: 'Major Transport Infrastructure',
    category: 'infrastructure',
    description: 'Major transport corridors and infrastructure',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: {
      bounds: [152.66, -27.54, 153.32, -27.05],
      states: ['QLD'],
      councils: ['brisbane'],
    },
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/City_Plan_2014_Regional_infrastructure_corridors_and_substations_overlay_Major_Transport_Infras/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.6,
      minZoom: 10,
      maxZoom: 22,
      fillColor: '#64748b',
      strokeColor: '#475569',
      strokeWidth: 2,
    },
    quality: 'authoritative',
    tags: ['transport', 'roads', 'rail', 'corridor', 'infrastructure'],
  },
  {
    id: 'brisbane-critical-infrastructure-assets',
    name: 'Critical Infrastructure Assets',
    category: 'infrastructure',
    description: 'Critical infrastructure assets and facilities',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: {
      bounds: [152.66, -27.54, 153.32, -27.05],
      states: ['QLD'],
      councils: ['brisbane'],
    },
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/Critical_infrastructure_and_movement_network_overlay_Assets_infrastructure_and_movement/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.7,
      minZoom: 10,
      maxZoom: 22,
      fillColor: '#0891b2',
      strokeColor: '#0e7490',
      strokeWidth: 2,
    },
    quality: 'authoritative',
    tags: ['critical', 'assets', 'infrastructure'],
  },
  {
    id: 'brisbane-critical-infrastructure-routes',
    name: 'Critical Infrastructure Routes',
    category: 'infrastructure',
    description: 'Critical movement and infrastructure routes',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: {
      bounds: [152.66, -27.54, 153.32, -27.05],
      states: ['QLD'],
      councils: ['brisbane'],
    },
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/Critical_infrastructure_and_movement_network_overlay_Routes/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.7,
      minZoom: 10,
      maxZoom: 22,
      strokeColor: '#0891b2',
      strokeWidth: 3,
    },
    quality: 'authoritative',
    tags: ['critical', 'routes', 'movement', 'infrastructure'],
  },
  {
    id: 'brisbane-bicycle-network',
    name: 'Bicycle Network',
    category: 'infrastructure',
    description: 'Planned and existing bicycle network',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: {
      bounds: [152.66, -27.54, 153.32, -27.05],
      states: ['QLD'],
      councils: ['brisbane'],
    },
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/Bicycle_network_overlay/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.7,
      minZoom: 12,
      maxZoom: 22,
      strokeColor: '#22c55e',
      strokeWidth: 2,
    },
    quality: 'authoritative',
    tags: ['bicycle', 'cycling', 'transport', 'infrastructure'],
  },
  {
    id: 'brisbane-priority-infrastructure-area',
    name: 'Priority Infrastructure Area',
    category: 'infrastructure',
    description: 'LGIP Priority Infrastructure Area boundaries',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: {
      bounds: [152.66, -27.54, 153.32, -27.05],
      states: ['QLD'],
      councils: ['brisbane'],
    },
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/City_Plan_2014_LGIP_Priority_Infrastructure_Area/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.4,
      minZoom: 10,
      maxZoom: 22,
      fillColor: '#f472b6',
      strokeColor: '#ec4899',
      strokeWidth: 2,
    },
    quality: 'authoritative',
    tags: ['priority', 'lgip', 'infrastructure', 'planning'],
  },

  // ============================================================================
  // URBAN UTILITIES - WATER NETWORK
  // Source: Queensland Urban Utilities Open Data
  // https://urbanutilities.com.au/about-us/who-we-are/asset-gis-information
  // ============================================================================
  {
    id: 'uu-water-mains',
    name: 'Water Mains',
    category: 'infrastructure',
    description: 'Water pressure mains and trunk mains',
    level: 'council',
    sourceId: 'urban-utilities',
    coverage: {
      bounds: [152.0, -27.54, 153.5, -27.0],
      states: ['QLD'],
      councils: ['brisbane', 'ipswich', 'lockyer-valley', 'scenic-rim', 'somerset'],
    },
    service: {
      type: 'arcgis-feature',
      url: `${UU_ARCGIS}/UU_Water_OpenData/FeatureServer/21`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.8,
      minZoom: 14,
      maxZoom: 22,
      strokeColor: '#0ea5e9',
      strokeWidth: 2,
      legend: [
        { label: 'Water Main', color: '#0ea5e9' },
      ],
    },
    quality: 'authoritative',
    tags: ['water', 'mains', 'pipes', 'infrastructure', 'urban-utilities'],
  },
  {
    id: 'uu-water-services',
    name: 'Water Service Connections',
    category: 'infrastructure',
    description: 'Water service connection points to properties',
    level: 'council',
    sourceId: 'urban-utilities',
    coverage: {
      bounds: [152.0, -27.54, 153.5, -27.0],
      states: ['QLD'],
      councils: ['brisbane', 'ipswich', 'lockyer-valley', 'scenic-rim', 'somerset'],
    },
    service: {
      type: 'arcgis-feature',
      url: `${UU_ARCGIS}/UU_Water_OpenData/FeatureServer/28`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.8,
      minZoom: 16,
      maxZoom: 22,
      strokeColor: '#38bdf8',
      strokeWidth: 1,
      legend: [
        { label: 'Service Connection', color: '#38bdf8' },
      ],
    },
    quality: 'authoritative',
    tags: ['water', 'service', 'connection', 'infrastructure', 'urban-utilities'],
  },
  {
    id: 'uu-water-hydrants',
    name: 'Fire Hydrants',
    category: 'infrastructure',
    description: 'Fire hydrant locations',
    level: 'council',
    sourceId: 'urban-utilities',
    coverage: {
      bounds: [152.0, -27.54, 153.5, -27.0],
      states: ['QLD'],
      councils: ['brisbane', 'ipswich', 'lockyer-valley', 'scenic-rim', 'somerset'],
    },
    service: {
      type: 'arcgis-feature',
      url: `${UU_ARCGIS}/UU_Water_OpenData/FeatureServer/15`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.9,
      minZoom: 16,
      maxZoom: 22,
      fillColor: '#1d4ed8',
      strokeColor: '#1e40af',
      strokeWidth: 1,
      legend: [
        { label: 'Fire Hydrant', color: '#1d4ed8' },
      ],
    },
    quality: 'authoritative',
    tags: ['water', 'hydrant', 'fire', 'infrastructure', 'urban-utilities'],
  },
  {
    id: 'uu-water-valves',
    name: 'Water Valves',
    category: 'infrastructure',
    description: 'Water system valves and control valves',
    level: 'council',
    sourceId: 'urban-utilities',
    coverage: {
      bounds: [152.0, -27.54, 153.5, -27.0],
      states: ['QLD'],
      councils: ['brisbane', 'ipswich', 'lockyer-valley', 'scenic-rim', 'somerset'],
    },
    service: {
      type: 'arcgis-feature',
      url: `${UU_ARCGIS}/UU_Water_OpenData/FeatureServer/33`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.8,
      minZoom: 17,
      maxZoom: 22,
      fillColor: '#0284c7',
      strokeColor: '#0369a1',
      strokeWidth: 1,
      legend: [
        { label: 'Water Valve', color: '#0284c7' },
      ],
    },
    quality: 'authoritative',
    tags: ['water', 'valve', 'infrastructure', 'urban-utilities'],
  },
  {
    id: 'uu-water-reservoirs',
    name: 'Water Reservoirs',
    category: 'infrastructure',
    description: 'Water storage reservoirs',
    level: 'council',
    sourceId: 'urban-utilities',
    coverage: {
      bounds: [152.0, -27.54, 153.5, -27.0],
      states: ['QLD'],
      councils: ['brisbane', 'ipswich', 'lockyer-valley', 'scenic-rim', 'somerset'],
    },
    service: {
      type: 'arcgis-feature',
      url: `${UU_ARCGIS}/UU_Water_OpenData/FeatureServer/25`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.7,
      minZoom: 12,
      maxZoom: 22,
      fillColor: '#0ea5e9',
      strokeColor: '#0284c7',
      strokeWidth: 2,
      legend: [
        { label: 'Water Reservoir', color: '#0ea5e9' },
      ],
    },
    quality: 'authoritative',
    tags: ['water', 'reservoir', 'storage', 'infrastructure', 'urban-utilities'],
  },
  {
    id: 'uu-water-pump-stations',
    name: 'Water Pump Stations',
    category: 'infrastructure',
    description: 'Water pump station locations',
    level: 'council',
    sourceId: 'urban-utilities',
    coverage: {
      bounds: [152.0, -27.54, 153.5, -27.0],
      states: ['QLD'],
      councils: ['brisbane', 'ipswich', 'lockyer-valley', 'scenic-rim', 'somerset'],
    },
    service: {
      type: 'arcgis-feature',
      url: `${UU_ARCGIS}/UU_Water_OpenData/FeatureServer/24`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.8,
      minZoom: 12,
      maxZoom: 22,
      fillColor: '#06b6d4',
      strokeColor: '#0891b2',
      strokeWidth: 2,
      legend: [
        { label: 'Water Pump Station', color: '#06b6d4' },
      ],
    },
    quality: 'authoritative',
    tags: ['water', 'pump', 'station', 'infrastructure', 'urban-utilities'],
  },

  // ============================================================================
  // URBAN UTILITIES - SEWER NETWORK
  // ============================================================================
  {
    id: 'uu-sewer-gravity-mains',
    name: 'Sewer Gravity Mains',
    category: 'infrastructure',
    description: 'Gravity sewer mains (main sewer pipes)',
    level: 'council',
    sourceId: 'urban-utilities',
    coverage: {
      bounds: [152.0, -27.54, 153.5, -27.0],
      states: ['QLD'],
      councils: ['brisbane', 'ipswich', 'lockyer-valley', 'scenic-rim', 'somerset'],
    },
    service: {
      type: 'arcgis-feature',
      url: `${UU_ARCGIS}/UU_Sewer_OpenData/FeatureServer/18`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.8,
      minZoom: 14,
      maxZoom: 22,
      strokeColor: '#dc2626',
      strokeWidth: 2,
      legend: [
        { label: 'Sewer Gravity Main', color: '#dc2626' },
      ],
    },
    quality: 'authoritative',
    tags: ['sewer', 'gravity', 'mains', 'pipes', 'infrastructure', 'urban-utilities'],
  },
  {
    id: 'uu-sewer-pressure-mains',
    name: 'Sewer Pressure Mains',
    category: 'infrastructure',
    description: 'Pressurized sewer mains (rising mains)',
    level: 'council',
    sourceId: 'urban-utilities',
    coverage: {
      bounds: [152.0, -27.54, 153.5, -27.0],
      states: ['QLD'],
      councils: ['brisbane', 'ipswich', 'lockyer-valley', 'scenic-rim', 'somerset'],
    },
    service: {
      type: 'arcgis-feature',
      url: `${UU_ARCGIS}/UU_Sewer_OpenData/FeatureServer/25`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.8,
      minZoom: 14,
      maxZoom: 22,
      strokeColor: '#ef4444',
      strokeWidth: 2,
      legend: [
        { label: 'Sewer Pressure Main', color: '#ef4444' },
      ],
    },
    quality: 'authoritative',
    tags: ['sewer', 'pressure', 'rising', 'mains', 'infrastructure', 'urban-utilities'],
  },
  {
    id: 'uu-sewer-services',
    name: 'Sewer Service Connections',
    category: 'infrastructure',
    description: 'Sewer service connection points to properties',
    level: 'council',
    sourceId: 'urban-utilities',
    coverage: {
      bounds: [152.0, -27.54, 153.5, -27.0],
      states: ['QLD'],
      councils: ['brisbane', 'ipswich', 'lockyer-valley', 'scenic-rim', 'somerset'],
    },
    service: {
      type: 'arcgis-feature',
      url: `${UU_ARCGIS}/UU_Sewer_OpenData/FeatureServer/30`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.8,
      minZoom: 16,
      maxZoom: 22,
      strokeColor: '#f87171',
      strokeWidth: 1,
      legend: [
        { label: 'Sewer Service', color: '#f87171' },
      ],
    },
    quality: 'authoritative',
    tags: ['sewer', 'service', 'connection', 'infrastructure', 'urban-utilities'],
  },
  {
    id: 'uu-sewer-manholes',
    name: 'Sewer Manholes',
    category: 'infrastructure',
    description: 'Sewer manhole/maintenance hole locations',
    level: 'council',
    sourceId: 'urban-utilities',
    coverage: {
      bounds: [152.0, -27.54, 153.5, -27.0],
      states: ['QLD'],
      councils: ['brisbane', 'ipswich', 'lockyer-valley', 'scenic-rim', 'somerset'],
    },
    service: {
      type: 'arcgis-feature',
      url: `${UU_ARCGIS}/UU_Sewer_OpenData/FeatureServer/20`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.8,
      minZoom: 16,
      maxZoom: 22,
      fillColor: '#b91c1c',
      strokeColor: '#991b1b',
      strokeWidth: 1,
      legend: [
        { label: 'Sewer Manhole', color: '#b91c1c' },
      ],
    },
    quality: 'authoritative',
    tags: ['sewer', 'manhole', 'maintenance', 'infrastructure', 'urban-utilities'],
  },
  {
    id: 'uu-sewer-pump-stations',
    name: 'Sewer Pump Stations',
    category: 'infrastructure',
    description: 'Sewage pump station locations',
    level: 'council',
    sourceId: 'urban-utilities',
    coverage: {
      bounds: [152.0, -27.54, 153.5, -27.0],
      states: ['QLD'],
      councils: ['brisbane', 'ipswich', 'lockyer-valley', 'scenic-rim', 'somerset'],
    },
    service: {
      type: 'arcgis-feature',
      url: `${UU_ARCGIS}/UU_Sewer_OpenData/FeatureServer/27`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.8,
      minZoom: 12,
      maxZoom: 22,
      fillColor: '#991b1b',
      strokeColor: '#7f1d1d',
      strokeWidth: 2,
      legend: [
        { label: 'Sewer Pump Station', color: '#991b1b' },
      ],
    },
    quality: 'authoritative',
    tags: ['sewer', 'pump', 'station', 'infrastructure', 'urban-utilities'],
  },
  {
    id: 'uu-sewer-vents',
    name: 'Sewer Vents',
    category: 'infrastructure',
    description: 'Sewer vent locations',
    level: 'council',
    sourceId: 'urban-utilities',
    coverage: {
      bounds: [152.0, -27.54, 153.5, -27.0],
      states: ['QLD'],
      councils: ['brisbane', 'ipswich', 'lockyer-valley', 'scenic-rim', 'somerset'],
    },
    service: {
      type: 'arcgis-feature',
      url: `${UU_ARCGIS}/UU_Sewer_OpenData/FeatureServer/34`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.7,
      minZoom: 17,
      maxZoom: 22,
      fillColor: '#fca5a5',
      strokeColor: '#f87171',
      strokeWidth: 1,
      legend: [
        { label: 'Sewer Vent', color: '#fca5a5' },
      ],
    },
    quality: 'authoritative',
    tags: ['sewer', 'vent', 'infrastructure', 'urban-utilities'],
  },
  // ============================================================================
  // TOPOGRAPHY
  // ============================================================================
  {
    id: 'brisbane-contours-1m',
    name: 'Contours (1m)',
    category: 'planning',
    description: '1 metre contour lines for detailed slope analysis',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: {
      bounds: [152.66, -27.54, 153.32, -27.05],
      states: ['QLD'],
      councils: ['brisbane'],
    },
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/Contours_1_metre/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.5,
      minZoom: 16,
      maxZoom: 22,
      strokeColor: '#a3a3a3',
      strokeWidth: 0.5,
    },
    quality: 'authoritative',
    tags: ['contours', 'topography', 'slope', 'elevation'],
  },
  {
    id: 'brisbane-contours-5m',
    name: 'Contours (5m)',
    category: 'planning',
    description: '5 metre contour lines for general slope assessment',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: {
      bounds: [152.66, -27.54, 153.32, -27.05],
      states: ['QLD'],
      councils: ['brisbane'],
    },
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/Contours_5_metre/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.6,
      minZoom: 13,
      maxZoom: 17,
      strokeColor: '#737373',
      strokeWidth: 1,
    },
    quality: 'authoritative',
    tags: ['contours', 'topography', 'slope', 'elevation'],
  },

  // ============================================================================
  // ADDITIONAL PLANNING
  // ============================================================================
  {
    id: 'brisbane-acid-sulfate-soils',
    name: 'Acid Sulfate Soils',
    category: 'environment',
    description: 'Acid sulfate soil areas requiring management during construction',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: {
      bounds: [152.66, -27.54, 153.32, -27.05],
      states: ['QLD'],
      councils: ['brisbane'],
    },
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/Acid_sulfate_soils_overlay/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.5,
      minZoom: 10,
      maxZoom: 22,
      fillColor: '#facc15',
      strokeColor: '#ca8a04',
      strokeWidth: 1,
    },
    quality: 'authoritative',
    tags: ['acid-sulfate', 'soils', 'construction', 'environment'],
  },
  {
    id: 'brisbane-dwelling-house',
    name: 'Dwelling House Overlay',
    category: 'planning',
    description: 'Areas with dwelling house character requirements',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: {
      bounds: [152.66, -27.54, 153.32, -27.05],
      states: ['QLD'],
      councils: ['brisbane'],
    },
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/Dwelling_house_overlay/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.4,
      minZoom: 12,
      maxZoom: 22,
      fillColor: '#fef3c7',
      strokeColor: '#d97706',
      strokeWidth: 1,
    },
    quality: 'authoritative',
    tags: ['dwelling', 'residential', 'character', 'planning'],
  },
  {
    id: 'brisbane-short-term-accommodation',
    name: 'Short Term Accommodation',
    category: 'planning',
    description: 'Areas where short term accommodation is restricted',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: {
      bounds: [152.66, -27.54, 153.32, -27.05],
      states: ['QLD'],
      councils: ['brisbane'],
    },
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/Short_term_accommodation_overlay/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.4,
      minZoom: 12,
      maxZoom: 22,
      fillColor: '#fda4af',
      strokeColor: '#e11d48',
      strokeWidth: 1,
    },
    quality: 'authoritative',
    tags: ['airbnb', 'short-term', 'accommodation', 'planning'],
  },
];

// Export layer count for reference
export const BRISBANE_LAYER_COUNT = BRISBANE_COUNCIL_LAYERS.length;
