/**
 * Brisbane City Council Overlay Layers
 *
 * Comprehensive planning overlays from Brisbane City Plan 2014
 * Source: Brisbane City Council Open Spatial Data
 * https://spatial-brisbane.opendata.arcgis.com/
 *
 * City Plan 2014 overlay reference (Part 8):
 * https://www.brisbane.qld.gov.au/planning-and-building/planning-guidelines-and-tools/brisbane-city-plan-2014/brisbane-city-plan-2014-mapping/overlays
 */

import { OverlayLayer } from './types';

const BCC_ARCGIS = 'https://services2.arcgis.com/dEKgZETqwmDAh1rP/arcgis/rest/services';
const UU_ARCGIS = 'https://services3.arcgis.com/ocUCNI2h4moKOpKX/arcgis/rest/services';

// Common BCC source URL bases
const BCC_OPEN_DATA = 'https://data.brisbane.qld.gov.au/explore/dataset';
const BCC_SPATIAL = 'https://spatial-brisbane.opendata.arcgis.com';
const BCC_CITYPLAN = 'https://cityplan.brisbane.qld.gov.au/eplan';
const BCC_OVERLAYS_PAGE = 'https://www.brisbane.qld.gov.au/planning-and-building/planning-guidelines-and-tools/brisbane-city-plan-2014/brisbane-city-plan-2014-mapping/overlays';
const BCC_FAM = 'https://fam.brisbane.qld.gov.au';

const BCC_COVERAGE = {
  bounds: [152.66, -27.54, 153.32, -27.05] as [number, number, number, number],
  states: ['QLD'] as ['QLD'],
  councils: ['brisbane'] as string[],
};

const UU_COVERAGE = {
  bounds: [152.0, -27.54, 153.5, -27.0] as [number, number, number, number],
  states: ['QLD'] as ['QLD'],
  councils: ['brisbane', 'ipswich', 'lockyer-valley', 'scenic-rim', 'somerset'] as string[],
};

export const BRISBANE_COUNCIL_LAYERS: OverlayLayer[] = [
  // ============================================================================
  // BOUNDARIES
  // ============================================================================
  {
    id: 'brisbane-property-boundaries',
    name: 'Property Boundaries',
    category: 'boundaries',
    description: 'Cadastral property boundaries (lot/plan)',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: BCC_COVERAGE,
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/property_boundaries_parcel/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.8,
      minZoom: 15,
      maxZoom: 22,
      fillColor: 'transparent',
      strokeColor: '#6b7280',
      strokeWidth: 1,
    },
    quality: 'authoritative',
    tags: ['cadastre', 'property', 'boundaries', 'lots'],
    sourceUrl: `${BCC_SPATIAL}/datasets/property-boundaries-parcel`,
  },

  // ============================================================================
  // PLANNING & ZONING
  // ============================================================================
  {
    id: 'brisbane-zoning',
    name: 'Zoning',
    category: 'planning',
    description: 'City Plan 2014 zoning designations',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: BCC_COVERAGE,
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/Zoning/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
      styleAttribute: 'LVL1_ZONE',
      styleMap: {
        'General residential': '#ffffbe',
        'Rural residential': '#ffcc99',
        'Emerging communities': '#ffe0b2',
        'Centre': '#cc3333',
        'Mixed use': '#ff6600',
        'Industry': '#9933ff',
        'Community facilities': '#ffff00',
        'Recreation and open space': '#00cc00',
        'Sport and recreation': '#66bb6a',
        'Environmental management and conservation': '#2e7d32',
        'Rural': '#c8e6c9',
        'Special purpose': '#999999',
      },
    },
    style: {
      opacity: 0.5,
      minZoom: 10,
      maxZoom: 22,
      legend: [
        { label: 'General Residential', color: '#ffffbe' },
        { label: 'Rural Residential', color: '#ffcc99' },
        { label: 'Emerging Communities', color: '#ffe0b2' },
        { label: 'Centre', color: '#cc3333' },
        { label: 'Mixed Use', color: '#ff6600' },
        { label: 'Industry', color: '#9933ff' },
        { label: 'Community Facilities', color: '#ffff00' },
        { label: 'Recreation & Open Space', color: '#00cc00' },
        { label: 'Sport & Recreation', color: '#66bb6a' },
        { label: 'Environmental Management', color: '#2e7d32' },
        { label: 'Rural', color: '#c8e6c9' },
        { label: 'Special Purpose', color: '#999999' },
      ],
    },
    quality: 'authoritative',
    lastUpdated: '2025-01-20',
    tags: ['zoning', 'land-use', 'planning'],
    sourceUrl: `${BCC_OPEN_DATA}/cp14-zoning-overlay`,
  },
  {
    id: 'brisbane-neighbourhood-plans',
    name: 'Neighbourhood Plans',
    category: 'planning',
    description: 'Neighbourhood plan boundaries',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: BCC_COVERAGE,
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/Neighbourhood_Plan_boundaries/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.4,
      minZoom: 11,
      maxZoom: 22,
      fillColor: '#8b5cf6',
      strokeColor: '#6d28d9',
      strokeWidth: 2,
    },
    quality: 'authoritative',
    tags: ['neighbourhood-plan', 'local-plan', 'planning'],
    sourceUrl: `${BCC_SPATIAL}/datasets/neighbourhood-plan-boundaries`,
  },

  // ============================================================================
  // FLOOD HAZARDS - AWARENESS LAYERS (Official FAM styling)
  // Colors and labels match Brisbane Flood Awareness Map (fam.brisbane.qld.gov.au)
  // ============================================================================
  {
    id: 'brisbane-flood-awareness-overall',
    name: 'Flood Likelihood (All Sources)',
    category: 'hazards',
    description: 'Combined flood likelihood from river, creek, overland and storm tide',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: BCC_COVERAGE,
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/Flood_Awareness_Flood_Risk_Overall/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.7,
      minZoom: 10,
      maxZoom: 22,
      legend: [
        { label: 'High likelihood (5% annual)', color: '#2166ac' },
        { label: 'Medium likelihood (1% annual)', color: '#67a9cf' },
        { label: 'Low likelihood (0.2% annual)', color: '#d1e5f0' },
        { label: 'Very low likelihood (0.05% annual)', color: '#f7f7f7' },
      ],
    },
    quality: 'authoritative',
    tags: ['flood', 'awareness', 'risk', 'combined', 'fam'],
    sourceUrl: BCC_FAM,
  },
  {
    id: 'brisbane-flood-awareness-river',
    name: 'Flood Awareness - River',
    category: 'hazards',
    description: 'Brisbane River flood likelihood zones',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: BCC_COVERAGE,
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/Flood_Awareness_River/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.7,
      minZoom: 10,
      maxZoom: 22,
      legend: [
        { label: 'High likelihood (5% annual)', color: '#2166ac' },
        { label: 'Medium likelihood (1% annual)', color: '#67a9cf' },
        { label: 'Low likelihood (0.2% annual)', color: '#d1e5f0' },
        { label: 'Very low likelihood (0.05% annual)', color: '#f7f7f7' },
      ],
    },
    quality: 'authoritative',
    tags: ['flood', 'river', 'awareness', 'fam'],
    sourceUrl: BCC_FAM,
  },
  {
    id: 'brisbane-flood-awareness-creek',
    name: 'Flood Awareness - Creek',
    category: 'hazards',
    description: 'Creek and waterway flood likelihood zones',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: BCC_COVERAGE,
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/Flood_Awareness_Creek/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.7,
      minZoom: 10,
      maxZoom: 22,
      legend: [
        { label: 'High likelihood (5% annual)', color: '#2166ac' },
        { label: 'Medium likelihood (1% annual)', color: '#67a9cf' },
        { label: 'Low likelihood (0.2% annual)', color: '#d1e5f0' },
        { label: 'Very low likelihood (0.05% annual)', color: '#f7f7f7' },
      ],
    },
    quality: 'authoritative',
    tags: ['flood', 'creek', 'awareness', 'fam'],
    sourceUrl: BCC_FAM,
  },
  {
    id: 'brisbane-flood-awareness-overland',
    name: 'Flood Awareness - Overland Flow',
    category: 'hazards',
    description: 'Overland flow flood impact zones',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: BCC_COVERAGE,
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/Flood_Awareness_Overland_Flow/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.7,
      minZoom: 12,
      maxZoom: 22,
      fillColor: '#d4b896',
      strokeColor: '#5e3c26',
      legend: [
        { label: 'High impact', color: '#5e3c26' },
        { label: 'Medium impact', color: '#d4b896' },
        { label: 'Low impact', color: '#f5e6d3' },
      ],
    },
    quality: 'authoritative',
    tags: ['flood', 'overland', 'awareness', 'fam'],
    sourceUrl: BCC_FAM,
  },
  // Historic flood extents
  {
    id: 'brisbane-flood-historic-2022',
    name: 'Historic Flood - February 2022',
    category: 'hazards',
    description: 'Observed flood extent from February 2022 event',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: BCC_COVERAGE,
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/Flood_Awareness_Historic_Brisbane_River_and_Creek_Floods_Feb2022/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.6,
      minZoom: 10,
      maxZoom: 22,
      fillColor: '#f4a7b9',
      strokeColor: '#e05780',
      legend: [
        { label: 'February 2022 extent', color: '#f4a7b9' },
      ],
    },
    quality: 'authoritative',
    tags: ['flood', 'historic', '2022', 'fam'],
    sourceUrl: BCC_FAM,
  },
  {
    id: 'brisbane-flood-historic-2011',
    name: 'Historic Flood - January 2011',
    category: 'hazards',
    description: 'Observed flood extent from January 2011 event',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: BCC_COVERAGE,
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/Flood_Awareness_Historic_Brisbane_River_Floods_Jan2011/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.6,
      minZoom: 10,
      maxZoom: 22,
      fillColor: '#7fcdbb',
      strokeColor: '#41ae76',
      legend: [
        { label: 'January 2011 extent', color: '#7fcdbb' },
      ],
    },
    quality: 'authoritative',
    tags: ['flood', 'historic', '2011', 'fam'],
    sourceUrl: BCC_FAM,
  },
  {
    id: 'brisbane-flood-historic-1974',
    name: 'Historic Flood - January 1974',
    category: 'hazards',
    description: 'Observed flood extent from January 1974 event',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: BCC_COVERAGE,
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/Flood_Awareness_Historic_Brisbane_River_Floods_Jan1974/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.6,
      minZoom: 10,
      maxZoom: 22,
      fillColor: '#9e9ac8',
      strokeColor: '#756bb1',
      legend: [
        { label: 'January 1974 extent', color: '#9e9ac8' },
      ],
    },
    quality: 'authoritative',
    tags: ['flood', 'historic', '1974', 'fam'],
    sourceUrl: BCC_FAM,
  },

  // ============================================================================
  // FLOOD HAZARDS - PLANNING OVERLAYS (Official City Plan overlays)
  // These are the regulatory flood planning overlays from Brisbane City Plan
  // City Plan 2014 Section 8.2.9
  // ============================================================================
  {
    id: 'brisbane-flood-river',
    name: 'Flood Planning - Brisbane River',
    category: 'hazards',
    description: 'Brisbane River flood planning areas (1-5) - City Plan overlay',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: BCC_COVERAGE,
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/Flood_overlay_Brisbane_River_flood_planning_area/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.6,
      minZoom: 10,
      maxZoom: 22,
      legend: [
        { label: 'Area 1 (Highest Risk)', color: '#08306b' },
        { label: 'Area 2a', color: '#2171b5' },
        { label: 'Area 2b', color: '#4292c6' },
        { label: 'Area 3', color: '#6baed6' },
        { label: 'Area 4', color: '#9ecae1' },
        { label: 'Area 5', color: '#c6dbef' },
      ],
    },
    quality: 'authoritative',
    tags: ['flood', 'river', 'hazard', 'brisbane-river', 'planning'],
    sourceUrl: `${BCC_OPEN_DATA}/cp14-flood-overlay-brisbane-river-flood-planning-area`,
  },
  {
    id: 'brisbane-flood-creek',
    name: 'Flood - Creek/Waterway',
    category: 'hazards',
    description: 'Creek and waterway flood planning areas',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: BCC_COVERAGE,
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/Flood_overlay_Creek_waterway_flood_planning_area/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.6,
      minZoom: 10,
      maxZoom: 22,
      legend: [
        { label: 'Area 1 (Highest Risk)', color: '#08306b' },
        { label: 'Area 2', color: '#2171b5' },
        { label: 'Area 3', color: '#4292c6' },
        { label: 'Area 4', color: '#6baed6' },
        { label: 'Area 5', color: '#9ecae1' },
      ],
    },
    quality: 'authoritative',
    tags: ['flood', 'creek', 'waterway', 'hazard'],
    sourceUrl: `${BCC_OPEN_DATA}/cp14-flood-overlay-creek-waterway-flood-planning-area`,
  },
  {
    id: 'brisbane-flood-overland',
    name: 'Flood - Overland Flow',
    category: 'hazards',
    description: 'Overland flow flood planning areas',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: BCC_COVERAGE,
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/Flood_overlay_Overland_flow/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.5,
      minZoom: 12,
      maxZoom: 22,
      fillColor: '#60a5fa',
      strokeColor: '#2563eb',
      strokeWidth: 1,
    },
    quality: 'authoritative',
    tags: ['flood', 'overland-flow', 'stormwater', 'hazard'],
    sourceUrl: `${BCC_OPEN_DATA}/cp14-flood-overlay-overland-flow`,
  },

  // ============================================================================
  // OTHER HAZARDS
  // ============================================================================
  // City Plan 2014 Section 8.2.4
  {
    id: 'brisbane-bushfire',
    name: 'Bushfire Overlay',
    category: 'hazards',
    description: 'Bushfire hazard areas and buffer zones',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: BCC_COVERAGE,
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/Bushfire_overlay/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.6,
      minZoom: 10,
      maxZoom: 22,
      legend: [
        { label: 'High Hazard Area', color: '#dc2626' },
        { label: 'Medium Hazard Area', color: '#f97316' },
        { label: 'Potential Impact Buffer', color: '#fbbf24' },
      ],
    },
    quality: 'authoritative',
    tags: ['bushfire', 'fire', 'hazard', 'bal'],
    sourceUrl: `${BCC_OPEN_DATA}/cp14-bushfire-overlay`,
  },
  // City Plan 2014 Section 8.2.14
  {
    id: 'brisbane-landslide',
    name: 'Landslide Overlay',
    category: 'hazards',
    description: 'Landslide susceptibility areas',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: BCC_COVERAGE,
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/Landslide_overlay/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.6,
      minZoom: 10,
      maxZoom: 22,
      fillColor: '#92400e',
      strokeColor: '#78350f',
      strokeWidth: 1,
    },
    quality: 'authoritative',
    tags: ['landslide', 'geotechnical', 'slope', 'hazard'],
    sourceUrl: `${BCC_OPEN_DATA}/cp14-landslide-overlay`,
  },
  // City Plan 2014 Section 8.2.5 - Coastal Hazard Overlay
  {
    id: 'brisbane-storm-tide',
    name: 'Coastal - Storm Tide',
    category: 'hazards',
    description: 'Storm tide inundation areas',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: BCC_COVERAGE,
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/Coastal_hazard_overlay_Storm_tide/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.6,
      minZoom: 10,
      maxZoom: 22,
      legend: [
        { label: 'High Storm Tide', color: '#1e40af' },
        { label: 'Medium Storm Tide', color: '#06b6d4' },
      ],
    },
    quality: 'authoritative',
    tags: ['coastal', 'storm-tide', 'inundation', 'hazard'],
    sourceUrl: `${BCC_OPEN_DATA}/cp14-coastal-hazard-overlay-storm-tide`,
  },
  {
    id: 'brisbane-coastal-erosion',
    name: 'Coastal - Erosion Prone',
    category: 'hazards',
    description: 'Coastal erosion prone areas',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: BCC_COVERAGE,
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/Coastal_hazard_overlay_coastal_erosion/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.6,
      minZoom: 10,
      maxZoom: 22,
      fillColor: '#0369a1',
      strokeColor: '#075985',
      strokeWidth: 1,
    },
    quality: 'authoritative',
    tags: ['coastal', 'erosion', 'hazard'],
    sourceUrl: `${BCC_OPEN_DATA}/cp14-coastal-hazard-overlay-coastal-erosion`,
  },
  {
    id: 'brisbane-sea-level-rise',
    name: 'Coastal - Sea Level Rise',
    category: 'hazards',
    description: 'Projected sea level rise impact areas',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: BCC_COVERAGE,
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/Coastal_hazard_overlay_Sea_level_rise/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.5,
      minZoom: 10,
      maxZoom: 22,
      fillColor: '#0284c7',
      strokeColor: '#0369a1',
      strokeWidth: 1,
    },
    quality: 'authoritative',
    tags: ['coastal', 'sea-level', 'climate', 'hazard'],
    sourceUrl: `${BCC_OPEN_DATA}/cp14-coastal-hazard-overlay-sea-level-rise`,
  },
  {
    id: 'brisbane-coastal-management',
    name: 'Coastal Management District',
    category: 'hazards',
    description: 'Coastal management district areas',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: BCC_COVERAGE,
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/Coastal_hazard_overlay_Coastal_management_district/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.4,
      minZoom: 10,
      maxZoom: 22,
      fillColor: '#38bdf8',
      strokeColor: '#0ea5e9',
      strokeWidth: 1,
    },
    quality: 'authoritative',
    tags: ['coastal', 'management', 'hazard'],
    sourceUrl: `${BCC_OPEN_DATA}/cp14-coastal-hazard-overlay-coastal-management-district`,
  },
  // City Plan 2014 Section 8.2.1 - Acid Sulfate Soils
  {
    id: 'brisbane-acid-sulfate-soils',
    name: 'Acid Sulfate Soils',
    category: 'environment',
    description: 'Acid sulfate soil areas requiring management during construction',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: BCC_COVERAGE,
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/City_Plan_2014_PotentialAndActual_acid_sulfate_soils_overlay/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.5,
      minZoom: 10,
      maxZoom: 22,
      fillColor: '#facc15',
      strokeColor: '#ca8a04',
      strokeWidth: 1,
    },
    quality: 'authoritative',
    tags: ['acid-sulfate', 'soils', 'construction', 'environment'],
    sourceUrl: `${BCC_OPEN_DATA}/cp14-potential-and-actual-acid-sulfate-soils`,
  },

  // ============================================================================
  // ENVIRONMENT
  // ============================================================================
  // City Plan 2014 Section 8.2.3
  {
    id: 'brisbane-biodiversity',
    name: 'Biodiversity Areas',
    category: 'environment',
    description: 'Areas of ecological significance',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: BCC_COVERAGE,
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/Biodiversity_areas_overlay_Biodiversity_areas/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.5,
      minZoom: 10,
      maxZoom: 22,
      legend: [
        { label: 'High Ecological Significance', color: '#166534' },
        { label: 'General Ecological Significance', color: '#4ade80' },
        { label: 'Strategic Biodiversity Area', color: '#86efac' },
      ],
    },
    quality: 'authoritative',
    tags: ['biodiversity', 'ecology', 'vegetation', 'environment'],
    sourceUrl: `${BCC_OPEN_DATA}/cp14-biodiversity-areas-overlay-biodiversity-areas`,
  },
  {
    id: 'brisbane-koala-habitat',
    name: 'Koala Habitat Areas',
    category: 'environment',
    description: 'Koala habitat protection areas',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: BCC_COVERAGE,
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/Biodiversity_areas_overlay_Koala_habitat_areas/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.5,
      minZoom: 10,
      maxZoom: 22,
      fillColor: '#65a30d',
      strokeColor: '#3f6212',
      strokeWidth: 1,
    },
    quality: 'authoritative',
    tags: ['koala', 'habitat', 'wildlife', 'environment'],
    sourceUrl: `${BCC_OPEN_DATA}/cp14-biodiversity-areas-overlay-koala-habitat-areas`,
  },
  // City Plan 2014 Section 8.2.22
  {
    id: 'brisbane-waterway-corridor',
    name: 'Waterway Corridors',
    category: 'environment',
    description: 'Natural waterway setback and buffer areas',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: BCC_COVERAGE,
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/Waterway_corridors_overlay/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.5,
      minZoom: 12,
      maxZoom: 22,
      legend: [
        { label: 'Core Waterway', color: '#0ea5e9' },
        { label: 'Corridor Buffer', color: '#7dd3fc' },
      ],
    },
    quality: 'authoritative',
    tags: ['waterway', 'creek', 'river', 'setback', 'environment'],
    sourceUrl: `${BCC_OPEN_DATA}/cp14-waterway-corridors-overlay-waterway-corridors`,
  },
  // City Plan 2014 Section 8.2.17
  {
    id: 'brisbane-scenic-amenity',
    name: 'Scenic Amenity',
    category: 'environment',
    description: 'Areas of high scenic/visual amenity value',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: BCC_COVERAGE,
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/Scenic_amenity_overlay/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.4,
      minZoom: 10,
      maxZoom: 22,
      legend: [
        { label: 'Ridge Line', color: '#059669' },
        { label: 'Scenic Route', color: '#10b981' },
        { label: 'Significant Vegetation', color: '#34d399' },
      ],
    },
    quality: 'authoritative',
    tags: ['scenic', 'amenity', 'visual', 'views', 'environment'],
    sourceUrl: `${BCC_OPEN_DATA}/cp14-scenic-amenity-overlay`,
  },
  // City Plan 2014 Section 8.2.18 - Significant Landscape Tree (NEW)
  {
    id: 'brisbane-significant-landscape-tree',
    name: 'Significant Landscape Trees',
    category: 'environment',
    description: 'Protected significant landscape trees',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: BCC_COVERAGE,
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/Significant_landscape_tree_overlay/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.7,
      minZoom: 14,
      maxZoom: 22,
      fillColor: '#15803d',
      strokeColor: '#166534',
      strokeWidth: 2,
    },
    quality: 'authoritative',
    tags: ['tree', 'landscape', 'significant', 'vegetation', 'environment'],
    sourceUrl: `${BCC_OPEN_DATA}/cp14-significant-landscape-tree-overlay`,
  },

  // ============================================================================
  // PLANNING CONTROLS
  // ============================================================================
  {
    id: 'brisbane-building-height',
    name: 'Building Height Limits',
    category: 'planning',
    description: 'Maximum building height zones',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: BCC_COVERAGE,
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/Building_height_overlay/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.5,
      minZoom: 12,
      maxZoom: 22,
      legend: [
        { label: '3 storeys (9.5m)', color: '#fef3c7' },
        { label: '5 storeys (15m)', color: '#fde68a' },
        { label: '8 storeys (25m)', color: '#fcd34d' },
        { label: '15 storeys (45m)', color: '#f59e0b' },
        { label: '25+ storeys', color: '#d97706' },
      ],
    },
    quality: 'authoritative',
    tags: ['height', 'building', 'storeys', 'planning'],
    sourceUrl: `${BCC_OPEN_DATA}/cp14-building-height-overlay`,
  },
  // City Plan 2014 Section 8.2.19 - Traditional Building Character
  {
    id: 'brisbane-character-residential',
    name: 'Traditional Building Character',
    category: 'planning',
    description: 'Traditional building character areas with design controls',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: BCC_COVERAGE,
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/Traditional_building_character_overlay/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.5,
      minZoom: 12,
      maxZoom: 22,
      legend: [
        { label: 'Pre-1946 Character', color: '#c084fc' },
        { label: 'Demolition Control', color: '#a855f7' },
      ],
    },
    quality: 'authoritative',
    tags: ['character', 'heritage', 'traditional', 'demolition', 'planning'],
    sourceUrl: `${BCC_OPEN_DATA}/cp14-traditional-building-character-overlay`,
  },
  // City Plan 2014 Section 8.2.7 - Dwelling House Character
  {
    id: 'brisbane-dwelling-house',
    name: 'Dwelling House Character Overlay',
    category: 'planning',
    description: 'Areas with dwelling house character requirements',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: BCC_COVERAGE,
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/Dwelling_house_character_overlay/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.4,
      minZoom: 12,
      maxZoom: 22,
      fillColor: '#fef3c7',
      strokeColor: '#d97706',
      strokeWidth: 1,
    },
    quality: 'authoritative',
    tags: ['dwelling', 'residential', 'character', 'planning'],
    sourceUrl: `${BCC_OPEN_DATA}/cp14-dwelling-house-character-overlay`,
  },
  // City Plan 2014 Section 8.2.15 - Pre-1911 Building (NEW)
  {
    id: 'brisbane-pre1911-building',
    name: 'Pre-1911 Building Overlay',
    category: 'planning',
    description: 'Buildings constructed before 1911 with demolition controls',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: BCC_COVERAGE,
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/Pre1911_building_overlay/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.6,
      minZoom: 13,
      maxZoom: 22,
      fillColor: '#d946ef',
      strokeColor: '#a21caf',
      strokeWidth: 1,
    },
    quality: 'authoritative',
    tags: ['pre-1911', 'building', 'heritage', 'demolition', 'planning'],
    sourceUrl: `${BCC_OPEN_DATA}/cp14-pre-1911-building-overlay`,
  },
  // Commercial Character Building (NEW)
  {
    id: 'brisbane-commercial-character',
    name: 'Commercial Character Building',
    category: 'planning',
    description: 'Commercial buildings with character design controls',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: BCC_COVERAGE,
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/Commercial_character_building_overlay/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.5,
      minZoom: 13,
      maxZoom: 22,
      fillColor: '#e879f9',
      strokeColor: '#c026d3',
      strokeWidth: 1,
    },
    quality: 'authoritative',
    tags: ['commercial', 'character', 'building', 'planning'],
    sourceUrl: `${BCC_OPEN_DATA}/cp14-commercial-character-building-overlay`,
  },
  // City Plan 2014 Section 8.2.2 - Airport Environs
  {
    id: 'brisbane-airport-environs',
    name: 'Airport Environs Overlay',
    category: 'planning',
    description: 'Airport noise corridors and height restrictions',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: BCC_COVERAGE,
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/City_Plan_2014_Airport_environs_overlay_Australian_Noise_Exposure_Forecast_ANEF/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.4,
      minZoom: 10,
      maxZoom: 22,
      legend: [
        { label: 'ANEF 25-30 (High Noise)', color: '#ef4444' },
        { label: 'ANEF 20-25', color: '#f97316' },
        { label: 'Light Limitation', color: '#fbbf24' },
        { label: 'Height Restriction', color: '#3b82f6' },
      ],
    },
    quality: 'authoritative',
    tags: ['airport', 'noise', 'anef', 'flight-path', 'planning'],
    sourceUrl: `${BCC_OPEN_DATA}/cp14-airport-environs-overlay-obstacle-limitation-surfaces-ols-boundary`,
  },
  // City Plan 2014 Section 8.2.21 - Transport Noise Corridor
  {
    id: 'brisbane-transport-noise',
    name: 'Transport Noise Corridor',
    category: 'planning',
    description: 'Road and rail noise impact areas',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: BCC_COVERAGE,
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/City_Plan_2014_Transport_noise_corridor_overlay_Brisbane_road_centreline/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.5,
      minZoom: 12,
      maxZoom: 22,
      legend: [
        { label: 'Road Noise Corridor', color: '#64748b' },
        { label: 'Rail Noise Corridor', color: '#475569' },
      ],
    },
    quality: 'authoritative',
    tags: ['noise', 'transport', 'road', 'rail', 'planning'],
    sourceUrl: `${BCC_OPEN_DATA}/cp14-transport-noise-corridor-overlay`,
  },
  // City Plan 2014 Section 8.2.20 - Transport Air Quality Corridor (NEW)
  {
    id: 'brisbane-transport-air-quality',
    name: 'Transport Air Quality Corridor',
    category: 'planning',
    description: 'Areas affected by transport-related air quality impacts',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: BCC_COVERAGE,
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/City_Plan_2014_Transport_air_quality_corridor_overlay_Transport_routes/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.5,
      minZoom: 12,
      maxZoom: 22,
      strokeColor: '#78716c',
      strokeWidth: 3,
    },
    quality: 'authoritative',
    tags: ['air-quality', 'transport', 'corridor', 'planning'],
    sourceUrl: `${BCC_OPEN_DATA}/cp14-transport-air-quality-corridor-overlay`,
  },
  // City Plan 2014 Section 8.2.8 - Extractive Resources
  {
    id: 'brisbane-extractive-resources',
    name: 'Extractive Resources',
    category: 'planning',
    description: 'Extractive industry (quarry) buffer areas',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: BCC_COVERAGE,
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/Extractive_resources_Key_resource_area/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.5,
      minZoom: 10,
      maxZoom: 22,
      legend: [
        { label: 'Key Resource Area', color: '#78716c' },
        { label: 'Separation Area', color: '#a8a29e' },
      ],
    },
    quality: 'authoritative',
    tags: ['extractive', 'quarry', 'mining', 'resources', 'planning'],
    sourceUrl: `${BCC_OPEN_DATA}/cp14-extractive-resources-overlay-mining-tenement`,
  },
  {
    id: 'brisbane-special-entertainment',
    name: 'Special Entertainment Precinct',
    category: 'planning',
    description: 'Areas with relaxed noise controls for entertainment venues',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: BCC_COVERAGE,
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/Special_entertainment_precinct_overlay/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.5,
      minZoom: 12,
      maxZoom: 22,
      fillColor: '#f472b6',
      strokeColor: '#ec4899',
      strokeWidth: 2,
    },
    quality: 'authoritative',
    tags: ['entertainment', 'fortitude-valley', 'noise', 'nightlife', 'planning'],
    sourceUrl: `${BCC_SPATIAL}/datasets/special-entertainment-precinct-overlay`,
  },
  {
    id: 'brisbane-short-term-accommodation',
    name: 'Short Term Accommodation',
    category: 'planning',
    description: 'Areas where short term accommodation is restricted',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: BCC_COVERAGE,
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/Short_term_accommodation_overlay/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.4,
      minZoom: 12,
      maxZoom: 22,
      fillColor: '#fda4af',
      strokeColor: '#e11d48',
      strokeWidth: 1,
    },
    quality: 'authoritative',
    tags: ['airbnb', 'short-term', 'accommodation', 'planning'],
    sourceUrl: `${BCC_SPATIAL}/datasets/short-term-accommodation-overlay`,
  },
  // City Plan 2014 Section 8.2.12 - Key Civic Space and Iconic Vista (NEW)
  {
    id: 'brisbane-key-civic-vista',
    name: 'Key Civic Space & Iconic Vista',
    category: 'planning',
    description: 'Protected civic spaces and view corridors',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: BCC_COVERAGE,
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/City_Plan_2014_Key_Civic_Iconic_Vista/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.5,
      minZoom: 12,
      maxZoom: 22,
      fillColor: '#818cf8',
      strokeColor: '#6366f1',
      strokeWidth: 2,
    },
    quality: 'authoritative',
    tags: ['civic', 'vista', 'view-corridor', 'planning'],
    sourceUrl: `${BCC_SPATIAL}/datasets/city-plan-2014-key-civic-iconic-vista`,
  },
  // Industrial Amenity Overlay (NEW)
  {
    id: 'brisbane-industrial-amenity',
    name: 'Industrial Amenity',
    category: 'planning',
    description: 'Industrial areas with amenity requirements for adjacent uses',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: BCC_COVERAGE,
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/Industrial_amenity_overlay/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.4,
      minZoom: 12,
      maxZoom: 22,
      fillColor: '#a78bfa',
      strokeColor: '#7c3aed',
      strokeWidth: 1,
    },
    quality: 'authoritative',
    tags: ['industrial', 'amenity', 'buffer', 'planning'],
    sourceUrl: `${BCC_OPEN_DATA}/cp14-industrial-amenity-overlay`,
  },
  // Streetscape Hierarchy Overlay (NEW)
  {
    id: 'brisbane-streetscape-hierarchy',
    name: 'Streetscape Hierarchy',
    category: 'planning',
    description: 'Street classification for landscaping and design standards',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: BCC_COVERAGE,
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/City_Plan_2014_Streetscape_hierarchy_overlay_Streetscape_hierarchy/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.5,
      minZoom: 13,
      maxZoom: 22,
      strokeColor: '#16a34a',
      strokeWidth: 2,
    },
    quality: 'authoritative',
    tags: ['streetscape', 'hierarchy', 'landscaping', 'planning'],
    sourceUrl: `${BCC_OPEN_DATA}/cp14-streetscape-hierarchy-overlay-streetscape-hierarchy`,
  },
  // Active Frontages in Residential Zones (NEW)
  {
    id: 'brisbane-active-frontages',
    name: 'Active Frontages (Residential)',
    category: 'planning',
    description: 'Residential zones requiring active street frontage design',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: BCC_COVERAGE,
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/Active_frontages_in_residential_zones_overlay/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.5,
      minZoom: 13,
      maxZoom: 22,
      strokeColor: '#0d9488',
      strokeWidth: 2,
    },
    quality: 'authoritative',
    tags: ['active-frontage', 'residential', 'design', 'planning'],
    sourceUrl: `${BCC_SPATIAL}/datasets/active-frontages-in-residential-zones-overlay`,
  },
  // Dwelling House Overlay (separate from character)
  {
    id: 'brisbane-dwelling-house-overlay',
    name: 'Dwelling House Overlay',
    category: 'planning',
    description: 'Dwelling house siting and design requirements',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: BCC_COVERAGE,
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/Dwelling_house_overlay/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.4,
      minZoom: 12,
      maxZoom: 22,
      fillColor: '#fef9c3',
      strokeColor: '#ca8a04',
      strokeWidth: 1,
    },
    quality: 'authoritative',
    tags: ['dwelling', 'house', 'siting', 'planning'],
    sourceUrl: `${BCC_SPATIAL}/datasets/dwelling-house-overlay`,
  },

  // ============================================================================
  // HERITAGE
  // ============================================================================
  // City Plan 2014 Section 8.2.10
  {
    id: 'brisbane-heritage',
    name: 'Heritage Overlay',
    category: 'heritage',
    description: 'Local heritage places and adjoining areas',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: BCC_COVERAGE,
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/Heritage_overlay/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.6,
      minZoom: 12,
      maxZoom: 22,
      legend: [
        { label: 'Local Heritage Place', color: '#7c3aed' },
        { label: 'Area Adjoining Heritage', color: '#c4b5fd' },
      ],
    },
    quality: 'authoritative',
    tags: ['heritage', 'historic', 'conservation'],
    sourceUrl: `${BCC_OPEN_DATA}/cp14-heritage-overlay-local-heritage-area`,
  },
  // City Plan 2014 Section 8.2.13 - Landscape Heritage (NEW)
  {
    id: 'brisbane-landscape-heritage',
    name: 'Landscape Heritage',
    category: 'heritage',
    description: 'Areas of landscape heritage significance',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: BCC_COVERAGE,
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/Landscape_heritage_overlay/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.5,
      minZoom: 11,
      maxZoom: 22,
      fillColor: '#a78bfa',
      strokeColor: '#7c3aed',
      strokeWidth: 2,
    },
    quality: 'authoritative',
    tags: ['landscape', 'heritage', 'historic', 'conservation'],
    sourceUrl: `${BCC_OPEN_DATA}/cp14-landscape-heritage-overlay`,
  },

  // ============================================================================
  // INFRASTRUCTURE - LGIP (Local Government Infrastructure Plan)
  // ============================================================================
  {
    id: 'brisbane-lgip-stormwater-existing',
    name: 'LGIP Stormwater - Existing',
    category: 'infrastructure',
    description: 'Existing stormwater infrastructure (PFTI)',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: BCC_COVERAGE,
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/City_Plan_2014_LGIP_PFTI_Stormwater_Existing/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.7,
      minZoom: 12,
      maxZoom: 22,
      fillColor: '#0ea5e9',
      strokeColor: '#0284c7',
      strokeWidth: 2,
    },
    quality: 'authoritative',
    tags: ['stormwater', 'drainage', 'infrastructure', 'lgip', 'existing'],
    sourceUrl: `${BCC_SPATIAL}/datasets/city-plan-2014-lgip-pfti-stormwater-existing`,
  },
  {
    id: 'brisbane-lgip-stormwater-future',
    name: 'LGIP Stormwater - Future',
    category: 'infrastructure',
    description: 'Planned future stormwater infrastructure (PFTI)',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: BCC_COVERAGE,
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/City_Plan_2014_LGIP_PFTI_Stormwater_Future/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.6,
      minZoom: 12,
      maxZoom: 22,
      fillColor: '#38bdf8',
      strokeColor: '#0ea5e9',
      strokeWidth: 2,
      lineDashArray: [5, 5],
    },
    quality: 'authoritative',
    tags: ['stormwater', 'drainage', 'infrastructure', 'lgip', 'future', 'planned'],
    sourceUrl: `${BCC_SPATIAL}/datasets/city-plan-2014-lgip-pfti-stormwater-future`,
  },
  {
    id: 'brisbane-lgip-transport-existing',
    name: 'LGIP Transport - Existing',
    category: 'infrastructure',
    description: 'Existing transport infrastructure (PFTI)',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: BCC_COVERAGE,
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/City_Plan_2014_LGIP_PFTI_Transport_Existing/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.7,
      minZoom: 10,
      maxZoom: 22,
      fillColor: '#f97316',
      strokeColor: '#ea580c',
      strokeWidth: 2,
    },
    quality: 'authoritative',
    tags: ['transport', 'roads', 'infrastructure', 'lgip', 'existing'],
    sourceUrl: `${BCC_SPATIAL}/datasets/city-plan-2014-lgip-pfti-transport-existing`,
  },
  {
    id: 'brisbane-lgip-transport-future',
    name: 'LGIP Transport - Future',
    category: 'infrastructure',
    description: 'Planned future transport infrastructure (PFTI)',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: BCC_COVERAGE,
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/City_Plan_2014_LGIP_PFTI_Transport_Future/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.6,
      minZoom: 10,
      maxZoom: 22,
      fillColor: '#fb923c',
      strokeColor: '#f97316',
      strokeWidth: 2,
      lineDashArray: [5, 5],
    },
    quality: 'authoritative',
    tags: ['transport', 'roads', 'infrastructure', 'lgip', 'future', 'planned'],
    sourceUrl: `${BCC_SPATIAL}/datasets/city-plan-2014-lgip-pfti-transport-future`,
  },
  {
    id: 'brisbane-lgip-parks-existing',
    name: 'LGIP Parks & Community - Existing',
    category: 'infrastructure',
    description: 'Existing parks and community facilities (PFTI)',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: BCC_COVERAGE,
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/City_Plan_2014_LGIP_PFTI_Parks_and_Community_Facilities_Existing/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.6,
      minZoom: 10,
      maxZoom: 22,
      fillColor: '#22c55e',
      strokeColor: '#16a34a',
      strokeWidth: 2,
    },
    quality: 'authoritative',
    tags: ['parks', 'community', 'recreation', 'infrastructure', 'lgip', 'existing'],
    sourceUrl: `${BCC_SPATIAL}/datasets/city-plan-2014-lgip-pfti-parks-and-community-facilities-existing`,
  },
  {
    id: 'brisbane-lgip-parks-future',
    name: 'LGIP Parks & Community - Future',
    category: 'infrastructure',
    description: 'Planned future parks and community facilities (PFTI)',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: BCC_COVERAGE,
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/City_Plan_2014_LGIP_PFTI_Parks_and_Community_Facilities_Future/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.5,
      minZoom: 10,
      maxZoom: 22,
      fillColor: '#4ade80',
      strokeColor: '#22c55e',
      strokeWidth: 2,
      lineDashArray: [5, 5],
    },
    quality: 'authoritative',
    tags: ['parks', 'community', 'recreation', 'infrastructure', 'lgip', 'future', 'planned'],
    sourceUrl: `${BCC_SPATIAL}/datasets/city-plan-2014-lgip-pfti-parks-and-community-facilities-future`,
  },
  {
    id: 'brisbane-lgip-service-catchments',
    name: 'LGIP Service Catchments',
    category: 'infrastructure',
    description: 'Local government infrastructure plan service catchment areas',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: BCC_COVERAGE,
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/City_Plan_2014_LGIP_Service_Catchments/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.3,
      minZoom: 10,
      maxZoom: 22,
      fillColor: '#a855f7',
      strokeColor: '#9333ea',
      strokeWidth: 1,
    },
    quality: 'authoritative',
    tags: ['service-catchment', 'infrastructure', 'lgip', 'planning'],
    sourceUrl: `${BCC_SPATIAL}/datasets/city-plan-2014-lgip-service-catchments`,
  },
  {
    id: 'brisbane-sewer-areas',
    name: 'Sewer Service Areas',
    category: 'infrastructure',
    description: 'Detail plan areas for sewer infrastructure',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: BCC_COVERAGE,
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/detail_plan_areas_sewer/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.4,
      minZoom: 10,
      maxZoom: 22,
      fillColor: '#8b5cf6',
      strokeColor: '#7c3aed',
      strokeWidth: 1,
    },
    quality: 'authoritative',
    tags: ['sewer', 'wastewater', 'infrastructure', 'utilities'],
    sourceUrl: `${BCC_SPATIAL}/datasets/detail-plan-areas-sewer`,
  },
  // City Plan 2014 Section 8.2.16 - Regional Infrastructure
  {
    id: 'brisbane-high-voltage-powerlines',
    name: 'High Voltage Powerlines',
    category: 'infrastructure',
    description: 'High voltage electricity transmission lines',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: BCC_COVERAGE,
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/Regional_infrastructure_corridors_and_substations_overlay_High_voltage_powerline/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.8,
      minZoom: 10,
      maxZoom: 22,
      strokeColor: '#dc2626',
      strokeWidth: 2,
    },
    quality: 'authoritative',
    tags: ['power', 'electricity', 'high-voltage', 'transmission', 'infrastructure'],
    sourceUrl: `${BCC_OPEN_DATA}/cp14-regional-infrastructure-corridors-and-substations-overlay-high-voltage-powerline`,
  },
  {
    id: 'brisbane-high-voltage-easements',
    name: 'High Voltage Easements',
    category: 'infrastructure',
    description: 'Easements for high voltage electricity infrastructure',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: BCC_COVERAGE,
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/Regional_infrastructure_corridors_and_substations_overlay_High_voltage_easements/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.5,
      minZoom: 12,
      maxZoom: 22,
      fillColor: '#fca5a5',
      strokeColor: '#dc2626',
      strokeWidth: 1,
    },
    quality: 'authoritative',
    tags: ['power', 'electricity', 'easement', 'infrastructure'],
    sourceUrl: `${BCC_OPEN_DATA}/cp14-regional-infrastructure-corridors-and-substations-overlay-high-voltage-easements`,
  },
  {
    id: 'brisbane-substations',
    name: 'High Voltage Substations',
    category: 'infrastructure',
    description: 'Electrical substations',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: BCC_COVERAGE,
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/CP2014_Regional_infrastructure_overlay_High_voltage_substations/FeatureServer/1`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.8,
      minZoom: 10,
      maxZoom: 22,
      fillColor: '#fbbf24',
      strokeColor: '#f59e0b',
      strokeWidth: 2,
    },
    quality: 'authoritative',
    tags: ['power', 'electricity', 'substation', 'infrastructure'],
    sourceUrl: `${BCC_SPATIAL}/datasets/cp2014-regional-infrastructure-overlay-high-voltage-substations`,
  },
  {
    id: 'brisbane-petroleum-pipelines',
    name: 'Petroleum Pipelines',
    category: 'infrastructure',
    description: 'Major petroleum and gas pipeline corridors',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: BCC_COVERAGE,
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/Regional_infrastructure_corridors_and_substations_overlay_Petroleum_pipelines/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.8,
      minZoom: 10,
      maxZoom: 22,
      strokeColor: '#7c3aed',
      strokeWidth: 3,
    },
    quality: 'authoritative',
    tags: ['petroleum', 'gas', 'pipeline', 'infrastructure'],
    sourceUrl: `${BCC_OPEN_DATA}/cp14-regional-infrastructure-corridors-and-substations-overlay-petroleum-pipelines`,
  },
  {
    id: 'brisbane-major-transport-infrastructure',
    name: 'Major Transport Infrastructure',
    category: 'infrastructure',
    description: 'Major transport corridors and infrastructure',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: BCC_COVERAGE,
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/City_Plan_2014_Regional_infrastructure_corridors_and_substations_overlay_Major_Transport_Infras/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.6,
      minZoom: 10,
      maxZoom: 22,
      fillColor: '#64748b',
      strokeColor: '#475569',
      strokeWidth: 2,
    },
    quality: 'authoritative',
    tags: ['transport', 'roads', 'rail', 'corridor', 'infrastructure'],
    sourceUrl: `${BCC_SPATIAL}/datasets/city-plan-2014-regional-infrastructure-corridors-and-substations-overlay-major-transport-infras`,
  },
  {
    id: 'brisbane-critical-infrastructure-assets',
    name: 'Critical Infrastructure Assets',
    category: 'infrastructure',
    description: 'Critical infrastructure assets and facilities',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: BCC_COVERAGE,
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/Critical_infrastructure_and_movement_network_overlay_Assets_infrastructure_and_movement/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.7,
      minZoom: 10,
      maxZoom: 22,
      fillColor: '#0891b2',
      strokeColor: '#0e7490',
      strokeWidth: 2,
    },
    quality: 'authoritative',
    tags: ['critical', 'assets', 'infrastructure'],
    sourceUrl: `${BCC_SPATIAL}/datasets/critical-infrastructure-and-movement-network-overlay`,
  },
  {
    id: 'brisbane-critical-infrastructure-routes',
    name: 'Critical Infrastructure Routes',
    category: 'infrastructure',
    description: 'Critical movement and infrastructure routes',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: BCC_COVERAGE,
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/Critical_infrastructure_and_movement_network_overlay_Routes/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.7,
      minZoom: 10,
      maxZoom: 22,
      strokeColor: '#0891b2',
      strokeWidth: 3,
    },
    quality: 'authoritative',
    tags: ['critical', 'routes', 'movement', 'infrastructure'],
    sourceUrl: `${BCC_SPATIAL}/datasets/critical-infrastructure-and-movement-network-overlay-routes`,
  },
  {
    id: 'brisbane-bicycle-network',
    name: 'Bicycle Network',
    category: 'infrastructure',
    description: 'Planned and existing bicycle network',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: BCC_COVERAGE,
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/Bicycle_network_overlay/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.7,
      minZoom: 12,
      maxZoom: 22,
      strokeColor: '#22c55e',
      strokeWidth: 2,
    },
    quality: 'authoritative',
    tags: ['bicycle', 'cycling', 'transport', 'infrastructure'],
    sourceUrl: `${BCC_OPEN_DATA}/cp14-bicycle-network-overlay`,
  },
  {
    id: 'brisbane-priority-infrastructure-area',
    name: 'Priority Infrastructure Area',
    category: 'infrastructure',
    description: 'LGIP Priority Infrastructure Area boundaries',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: BCC_COVERAGE,
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/City_Plan_2014_LGIP_Priority_Infrastructure_Area/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.4,
      minZoom: 10,
      maxZoom: 22,
      fillColor: '#f472b6',
      strokeColor: '#ec4899',
      strokeWidth: 2,
    },
    quality: 'authoritative',
    tags: ['priority', 'lgip', 'infrastructure', 'planning'],
    sourceUrl: `${BCC_SPATIAL}/datasets/city-plan-2014-lgip-priority-infrastructure-area`,
  },

  // ============================================================================
  // URBAN UTILITIES - WATER NETWORK
  // Source: Queensland Urban Utilities Open Data
  // https://urbanutilities.com.au/about-us/who-we-are/asset-gis-information
  // ============================================================================
  {
    id: 'uu-water-mains',
    name: 'Water Mains',
    category: 'infrastructure',
    description: 'Water pressure mains and trunk mains',
    level: 'council',
    sourceId: 'urban-utilities',
    coverage: UU_COVERAGE,
    service: {
      type: 'arcgis-feature',
      url: `${UU_ARCGIS}/UU_Water_OpenData/FeatureServer/21`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.8,
      minZoom: 14,
      maxZoom: 22,
      strokeColor: '#0ea5e9',
      strokeWidth: 2,
      legend: [
        { label: 'Water Main', color: '#0ea5e9' },
      ],
    },
    quality: 'authoritative',
    tags: ['water', 'mains', 'pipes', 'infrastructure', 'urban-utilities'],
    sourceUrl: 'https://urbanutilities.com.au/about-us/who-we-are/asset-gis-information',
  },
  {
    id: 'uu-water-services',
    name: 'Water Service Connections',
    category: 'infrastructure',
    description: 'Water service connection points to properties',
    level: 'council',
    sourceId: 'urban-utilities',
    coverage: UU_COVERAGE,
    service: {
      type: 'arcgis-feature',
      url: `${UU_ARCGIS}/UU_Water_OpenData/FeatureServer/28`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.8,
      minZoom: 16,
      maxZoom: 22,
      strokeColor: '#38bdf8',
      strokeWidth: 1,
      legend: [
        { label: 'Service Connection', color: '#38bdf8' },
      ],
    },
    quality: 'authoritative',
    tags: ['water', 'service', 'connection', 'infrastructure', 'urban-utilities'],
    sourceUrl: 'https://urbanutilities.com.au/about-us/who-we-are/asset-gis-information',
  },
  {
    id: 'uu-water-hydrants',
    name: 'Fire Hydrants',
    category: 'infrastructure',
    description: 'Fire hydrant locations',
    level: 'council',
    sourceId: 'urban-utilities',
    coverage: UU_COVERAGE,
    service: {
      type: 'arcgis-feature',
      url: `${UU_ARCGIS}/UU_Water_OpenData/FeatureServer/15`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.9,
      minZoom: 16,
      maxZoom: 22,
      fillColor: '#1d4ed8',
      strokeColor: '#1e40af',
      strokeWidth: 1,
      legend: [
        { label: 'Fire Hydrant', color: '#1d4ed8' },
      ],
    },
    quality: 'authoritative',
    tags: ['water', 'hydrant', 'fire', 'infrastructure', 'urban-utilities'],
    sourceUrl: 'https://urbanutilities.com.au/about-us/who-we-are/asset-gis-information',
  },
  {
    id: 'uu-water-valves',
    name: 'Water Valves',
    category: 'infrastructure',
    description: 'Water system valves and control valves',
    level: 'council',
    sourceId: 'urban-utilities',
    coverage: UU_COVERAGE,
    service: {
      type: 'arcgis-feature',
      url: `${UU_ARCGIS}/UU_Water_OpenData/FeatureServer/33`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.8,
      minZoom: 17,
      maxZoom: 22,
      fillColor: '#0284c7',
      strokeColor: '#0369a1',
      strokeWidth: 1,
      legend: [
        { label: 'Water Valve', color: '#0284c7' },
      ],
    },
    quality: 'authoritative',
    tags: ['water', 'valve', 'infrastructure', 'urban-utilities'],
    sourceUrl: 'https://urbanutilities.com.au/about-us/who-we-are/asset-gis-information',
  },
  {
    id: 'uu-water-reservoirs',
    name: 'Water Reservoirs',
    category: 'infrastructure',
    description: 'Water storage reservoirs',
    level: 'council',
    sourceId: 'urban-utilities',
    coverage: UU_COVERAGE,
    service: {
      type: 'arcgis-feature',
      url: `${UU_ARCGIS}/UU_Water_OpenData/FeatureServer/25`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.7,
      minZoom: 12,
      maxZoom: 22,
      fillColor: '#0ea5e9',
      strokeColor: '#0284c7',
      strokeWidth: 2,
      legend: [
        { label: 'Water Reservoir', color: '#0ea5e9' },
      ],
    },
    quality: 'authoritative',
    tags: ['water', 'reservoir', 'storage', 'infrastructure', 'urban-utilities'],
    sourceUrl: 'https://urbanutilities.com.au/about-us/who-we-are/asset-gis-information',
  },
  {
    id: 'uu-water-pump-stations',
    name: 'Water Pump Stations',
    category: 'infrastructure',
    description: 'Water pump station locations',
    level: 'council',
    sourceId: 'urban-utilities',
    coverage: UU_COVERAGE,
    service: {
      type: 'arcgis-feature',
      url: `${UU_ARCGIS}/UU_Water_OpenData/FeatureServer/24`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.8,
      minZoom: 12,
      maxZoom: 22,
      fillColor: '#06b6d4',
      strokeColor: '#0891b2',
      strokeWidth: 2,
      legend: [
        { label: 'Water Pump Station', color: '#06b6d4' },
      ],
    },
    quality: 'authoritative',
    tags: ['water', 'pump', 'station', 'infrastructure', 'urban-utilities'],
    sourceUrl: 'https://urbanutilities.com.au/about-us/who-we-are/asset-gis-information',
  },

  // ============================================================================
  // URBAN UTILITIES - SEWER NETWORK
  // ============================================================================
  {
    id: 'uu-sewer-gravity-mains',
    name: 'Sewer Gravity Mains',
    category: 'infrastructure',
    description: 'Gravity sewer mains (main sewer pipes)',
    level: 'council',
    sourceId: 'urban-utilities',
    coverage: UU_COVERAGE,
    service: {
      type: 'arcgis-feature',
      url: `${UU_ARCGIS}/UU_Sewer_OpenData/FeatureServer/18`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.8,
      minZoom: 14,
      maxZoom: 22,
      strokeColor: '#dc2626',
      strokeWidth: 2,
      legend: [
        { label: 'Sewer Gravity Main', color: '#dc2626' },
      ],
    },
    quality: 'authoritative',
    tags: ['sewer', 'gravity', 'mains', 'pipes', 'infrastructure', 'urban-utilities'],
    sourceUrl: 'https://urbanutilities.com.au/about-us/who-we-are/asset-gis-information',
  },
  {
    id: 'uu-sewer-pressure-mains',
    name: 'Sewer Pressure Mains',
    category: 'infrastructure',
    description: 'Pressurized sewer mains (rising mains)',
    level: 'council',
    sourceId: 'urban-utilities',
    coverage: UU_COVERAGE,
    service: {
      type: 'arcgis-feature',
      url: `${UU_ARCGIS}/UU_Sewer_OpenData/FeatureServer/25`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.8,
      minZoom: 14,
      maxZoom: 22,
      strokeColor: '#ef4444',
      strokeWidth: 2,
      legend: [
        { label: 'Sewer Pressure Main', color: '#ef4444' },
      ],
    },
    quality: 'authoritative',
    tags: ['sewer', 'pressure', 'rising', 'mains', 'infrastructure', 'urban-utilities'],
    sourceUrl: 'https://urbanutilities.com.au/about-us/who-we-are/asset-gis-information',
  },
  {
    id: 'uu-sewer-services',
    name: 'Sewer Service Connections',
    category: 'infrastructure',
    description: 'Sewer service connection points to properties',
    level: 'council',
    sourceId: 'urban-utilities',
    coverage: UU_COVERAGE,
    service: {
      type: 'arcgis-feature',
      url: `${UU_ARCGIS}/UU_Sewer_OpenData/FeatureServer/30`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.8,
      minZoom: 16,
      maxZoom: 22,
      strokeColor: '#f87171',
      strokeWidth: 1,
      legend: [
        { label: 'Sewer Service', color: '#f87171' },
      ],
    },
    quality: 'authoritative',
    tags: ['sewer', 'service', 'connection', 'infrastructure', 'urban-utilities'],
    sourceUrl: 'https://urbanutilities.com.au/about-us/who-we-are/asset-gis-information',
  },
  {
    id: 'uu-sewer-manholes',
    name: 'Sewer Manholes',
    category: 'infrastructure',
    description: 'Sewer manhole/maintenance hole locations',
    level: 'council',
    sourceId: 'urban-utilities',
    coverage: UU_COVERAGE,
    service: {
      type: 'arcgis-feature',
      url: `${UU_ARCGIS}/UU_Sewer_OpenData/FeatureServer/20`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.8,
      minZoom: 16,
      maxZoom: 22,
      fillColor: '#b91c1c',
      strokeColor: '#991b1b',
      strokeWidth: 1,
      legend: [
        { label: 'Sewer Manhole', color: '#b91c1c' },
      ],
    },
    quality: 'authoritative',
    tags: ['sewer', 'manhole', 'maintenance', 'infrastructure', 'urban-utilities'],
    sourceUrl: 'https://urbanutilities.com.au/about-us/who-we-are/asset-gis-information',
  },
  {
    id: 'uu-sewer-pump-stations',
    name: 'Sewer Pump Stations',
    category: 'infrastructure',
    description: 'Sewage pump station locations',
    level: 'council',
    sourceId: 'urban-utilities',
    coverage: UU_COVERAGE,
    service: {
      type: 'arcgis-feature',
      url: `${UU_ARCGIS}/UU_Sewer_OpenData/FeatureServer/27`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.8,
      minZoom: 12,
      maxZoom: 22,
      fillColor: '#991b1b',
      strokeColor: '#7f1d1d',
      strokeWidth: 2,
      legend: [
        { label: 'Sewer Pump Station', color: '#991b1b' },
      ],
    },
    quality: 'authoritative',
    tags: ['sewer', 'pump', 'station', 'infrastructure', 'urban-utilities'],
    sourceUrl: 'https://urbanutilities.com.au/about-us/who-we-are/asset-gis-information',
  },
  {
    id: 'uu-sewer-vents',
    name: 'Sewer Vents',
    category: 'infrastructure',
    description: 'Sewer vent locations',
    level: 'council',
    sourceId: 'urban-utilities',
    coverage: UU_COVERAGE,
    service: {
      type: 'arcgis-feature',
      url: `${UU_ARCGIS}/UU_Sewer_OpenData/FeatureServer/34`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.7,
      minZoom: 17,
      maxZoom: 22,
      fillColor: '#fca5a5',
      strokeColor: '#f87171',
      strokeWidth: 1,
      legend: [
        { label: 'Sewer Vent', color: '#fca5a5' },
      ],
    },
    quality: 'authoritative',
    tags: ['sewer', 'vent', 'infrastructure', 'urban-utilities'],
    sourceUrl: 'https://urbanutilities.com.au/about-us/who-we-are/asset-gis-information',
  },

  // ============================================================================
  // TOPOGRAPHY
  // ============================================================================
  {
    id: 'brisbane-contours-1m',
    name: 'Contours (1m)',
    category: 'planning',
    description: '1 metre contour lines for detailed slope analysis',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: BCC_COVERAGE,
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/Contours_1_metre/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.5,
      minZoom: 16,
      maxZoom: 22,
      strokeColor: '#a3a3a3',
      strokeWidth: 0.5,
    },
    quality: 'authoritative',
    tags: ['contours', 'topography', 'slope', 'elevation'],
    sourceUrl: `${BCC_SPATIAL}/datasets/contours-1-metre`,
  },
  {
    id: 'brisbane-contours-5m',
    name: 'Contours (5m)',
    category: 'planning',
    description: '5 metre contour lines for general slope assessment',
    level: 'council',
    sourceId: 'brisbane-council',
    coverage: BCC_COVERAGE,
    service: {
      type: 'arcgis-feature',
      url: `${BCC_ARCGIS}/Contours_5_metre/FeatureServer/0`,
      format: 'geojson',
      requiresProxy: false,
    },
    style: {
      opacity: 0.6,
      minZoom: 13,
      maxZoom: 17,
      strokeColor: '#737373',
      strokeWidth: 1,
    },
    quality: 'authoritative',
    tags: ['contours', 'topography', 'slope', 'elevation'],
    sourceUrl: `${BCC_SPATIAL}/datasets/contours-5-metre`,
  },
];

// Export layer count for reference
export const BRISBANE_LAYER_COUNT = BRISBANE_COUNCIL_LAYERS.length;
